const paramData = {
  a: [
    'External enclosure status',
    'Antenna cover',
    'Box labels',
    'Hinges',
    'Locking mechanism',
    'Vents and mesh',
    'Doors',
    'Door sensors',
    'Meter(confirm Modem)',
    'Circuit Breaker',
    'Cable Jumpers',
    'Termination screws',
    'Termination Safety covers',
    'Termination separators',
    'Earth loops',
    'Earthing point',
    'Knock - out plates',
    'AC - DC converter',
    'CIU',
    'Cross arm (2pcs)',
    'Brackets (2pcs)',
    'L - mounting plate (4 pcs)',
    '3/4 by 2 bolts (12pcs)',
    '3/4 by 12 bolts (4pcs)',
    'Flat round washers (32pcs)'
  ],

  ag: [
    'DIN Rail Material (Galvanized Cold Rolled Carbon Steel)',
    'DIN Rail Dimension ((35x7.5 x1.0)mm)',
    'DIN Rail Length (100mm)',
    'Mounting Holes/Slots (Wood Screw Holes/Slots)',
    'Diameter of Mounting Holes (7mm)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  ah: [
    'Material (Hot Dip Galvanised Steel)',
    'D-Iron Manufacture (Drop Forged Manufacture)',
    'Thickness of D-Iron Body (mm)',
    'Width of D-Iron Body (mm)',
    'Approxmate Over Length of D-Iron (330mm)',
    'Number and Diameter of Holes (3 of D18mm)',
    'D-Iron Finish (Smooth Galvanised Finish)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  ai: [
    'Transformer Rating',
    'Operating Voltage (11kv & 33Kv)',
    'Vector group (three phase):(Dyn 11)',
    'Cooling type (ONAN)',
    'Transformer Type (Completely Self Protected)',
    'Lifting lugs (Minimum of two closed lifting lugs)',
    'Bushings (Should not be cracked)',
    'Transformer Body (No oil Leakage)',
    "Transformer Body Finish (Paint shouldn't Peel off and no signs of rust)",
    'Mounting (Mounting Brackests accessories should be provided)',
    'Eartrhing Terminals (Multiple Earthing Terminals should be provided)',
    'Surge Arresters (Pre- Installed on the Transformer, arresters shall be fitted with arcing horns)',
    'Surge Arresters Crossectional area (16sqmm)',
    'Transformer Sealing and Bolting (Sealed with a gaskate and sufficiently close tightened bolts and nuts)',
    'Name Plate (Fitted with a Stainless steel rating plate)',
    'Bush Terminal markings (Primary and Secondary terminal markings plainly and indelibly marked on the transformer)',
    'Number of steps/Tapping Positions (5)',
    'LV Bushing Creepage Distance (≥40mm)',
    'MV Bushing Creepage Distance (≥300mm)',
    'MV Bushing Creepage Distance (≥900mm)',
    'Current Transformer Construction (Pre- Installed in the Transformer LV Distribution box)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  aj: [
    'System Voltage',
    'Rated current (400A)',
    'Creepage distance',
    "Insulation Material (Polymeric and Shouldn't have any Damage)",
    'Mounting Accessories and Brackets',
    'Accessories Construction (Hot Deep Galv. Steel)',
    'Fusant (Correct rating Provided)',
    'Operation (Easily Operational with Stick.)',
    'Dimensions (Per Technical Drawing)',
    'Markings',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  ak: [
    'Earth rod Material (Copper cladded steel)',
    'Thickness of copper cladding (0.25mm minimum)',
    'Construction (Tappered portion, threaded portion with a tip)',
    'Dimensions (D-13mm)',
    'Length of copper earth rod (1.4-1.5m',
    'Length of tip (10-12mm',
    'Length of threaded portion (40-50mm',
    'Type of threading (Isometric type)',
    'Earth rod clamp (3mm thick',
    'Clamp material (tinned copper)',
    'Length of clamp (40-50mm)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  al: [
    'Mode of Construction (Forged in one piece and fully Polished)',
    'Material (All Steel Metal)',
    'Construction Style (Curved head with Long straight claws)',
    'Grip Material (Fiberglass or Nylon Vinyl deep cusion grip)',
    'Overall Length (31.8cm (12.5)',
    'Finish (Handle and Head are fully Polished)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  am: [
    'Eye Bolt Size',
    'Material (Hot Dip Galvanised Steel)',
    'Eye Bolt Manufacture (Drop Forged Manufacture)',
    'Length of eye bolt(mm)',
    'Length of threads(mm)',
    'Diameter of unthreaded part(mm)',
    'Diameter of Eye Bolt(mm)',
    'Nuts and Washers',
    'Thickness of Eye (mm)',
    'Length of Threaded part',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  an: [
    'Sheet metal thickness including coating (1.6mm)',
    'Material (mild steel plate)',
    'Door hinges construction (Door hinges concealed)',
    'Meter box colour (UMEME green)',
    'Transparent  glass hole dimesions (300mm long and 30mm wide (LxW)',
    'Transparent glass thickness (6mm)',
    'Thickness of internal wooden board (18mm)',
    'Dimensions of internal wooden board (Length (L) =490mm, Height (H) =520mm, Width (W) = 18mm)',
    'Number of Holes for incoming and outgoing cable (02)',
    'Diameter of holes for cable entry (50mm)',
    'Meter box louver construction (3 or 4 louvres of length 90mm, on both sides of the box  tapering down)',
    'Earthing Terminal bolt (35 x 9 mm made of galvanized iron earth with a washer)',
    'Locking system (A lock that only accommodates a standard padlock  and is not easy to tamper with. It shall be easy to  operate and lock):(The locking hole should be at a distance of 2mm from the door)',
    'The Meter Box body condition (Should not have any damages)',
    'Height of support stands (860mm)',
    'External dimensions of the box (Height (H) =600mm, Length (L) = 570mm)'
  ],
  ao: [
    'Parts of the Device',
    'Body Belt Material',
    'Body Belt Design',
    'Body Belt Stitching',
    'Material of Distribution Strap',
    'Stopping Cleat',
    'Labels',
    'Fixed Dual Slot D-Ring',
    'Labels',
    'Cynch-Lok Roller Adjuster (Strap)',
    'Fixed Dual Slot D-Ring (Strap)',
    'Accessories',
    'Manuals',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  ap: [
    'Operating Voltage ( LV; ≤ 1000V)',
    'Feeder pillar body',
    'Lifting lugs',
    'Feeder pillar Body Finish',
    'Feeder pillar bus bars(Ammeter of accuracy at least +/- 2.5%.,installed):(Voltmeter of accuracy at least at least +/-1.5%.)',
    'Coating Auto recloser Mounting brackets',
    'Eartrhing Terminals',
    ' One incomer and four or six or eight outgoing fused circuts (each three phase)',
    'Three current transformers ratio 1600/800/5, class 1.0 10VA',
    'Name Plate(Fitted with a Stainless steel rating plate)',
    ' Circuit identification/labelling facility',
    'Dimensions of feeder pillar',
    'The top cover of Feeder pillar shall have inclined surface(s) to avoid Accumulation of rain water. It shall have a canopy over the door',
    'MV Bushing Creepage Distance',
    ' 13A 3-pin switch socket outlet with plug (square pins)',
    'Ventilation louvres with anti-vermin baffles',
    'Phase barries  provided to prevent insertion of fuse links between contacts of different phases. The barrier shall be of material which does not readily support combustion',
    '3 phase 4-wire fuse unit',
    'Test certificates (Routine, type tests, National accreditation of supplier) and schematic wiring diagram'
  ]
};

export default paramData;
