const paramData = {
  a: [
    'External enclosure status',
    'Antenna cover',
    'Box labels',
    'Hinges',
    'Locking mechanism',
    'Vents and mesh',
    'Doors',
    'Door sensors',
    'Meter(confirm Modem)',
    'Circuit Breaker',
    'Cable Jumpers',
    'Termination screws',
    'Termination Safety covers',
    'Termination separators',
    'Earth loops',
    'Earthing point',
    'Knock - out plates',
    'AC - DC converter',
    'CIU',
    'Cross arm (2pcs)',
    'Brackets (2pcs)',
    'L - mounting plate (4 pcs)',
    '3/4 by 2 bolts (12pcs)',
    '3/4 by 12 bolts (4pcs)',
    'Flat round washers (32pcs)'
  ],
  b: [
    'Design Construction of  Hammer stapler	(All stainless steel construction)',
    'Handle (Should be soft grip)',
    'Performance (Strong penetrating power and quick excellent performance)',
    'Head Rotational Angle (Fixed)',
    'Working Condition (Multiple application)',
    'Staples (Stainless steel.- Galvanized)',
    'Staple  size  140 T50 (6 - 12 mm)',
    'Weight of Tool (light and versatile)',
    'Accessories (Full range of approved staples)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  c: [
    'End cap Size (state)',
    ' End cap  Material (UV stabilized insulation rubber)',
    'Design or Construction (Suitably designed for sealing the open ends of insulated conductors against water ingress)',
    'Installation (Can be held in installed position by elastic forces)',
    'Finish (Smooth and uniform thickness without any sharp edges)',
    'Test certificates (Routine, type tests)  provide'
  ],
  d: [
    'Material (Nylon/Polyester)',
    'Design (Factory spliced Eyes at both ends)',
    'Rope Diameter (0.5)',
    'Type (Double braided inner core with extra braided outer jacket)',
    'Colour (White with green tracer/Yellow)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  e: [
    'Material of the Box (Hard Plastic)',
    'External  enclosure appearance (Should be smooth with no damage)',
    'Bottom holes (4 holes D-22mm)',
    'Neutral Block-Pre installed (confirm)',
    'Dimensions of the box (L=310mm,W=110mm,H=118mm)',
    'Check for accessories to be provided (confirm)',
    'Current rating of the box 80-100A (confirm)',
    'Hinghes Opening with ease(confirm)',
    'Test certificate to be provided(confirm)'
  ],
  f: [
    'Material(Nylon/Polyester)',
    'Design (Factory spliced Eyes at both ends)',
    'Rope Diameter (1)',
    'Type (Double braided inner core with extra braided outer jacket)',
    'Colour (White with green tracer)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  g: [
    'Material (Aluminium/Glass fiber)',
    'Length (5.7m(18.6ft)',
    'Step Distance (28cm)',
    'Features (Work platform and Step Platform)',
    'Construction (Has Stabilizer Rubbers and can be turned into step/straight ladder)',
    'Finish (smooth finish)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  h: [
    'Material of Tape (Fibreglass covered with synthetic material)',
    'Material and Construction of Casing (Synthetic casing with tape-retraction winder handle.)',
    'Casing Finish (Vinyl-Coated Steel Casing)',
    'Length (50m)',
    'Band Width (12mm-13mm)',
    'Colour (Green/Blue, Black/White)',
    'Units of Measurement (Metric and Imperial)',
    'Finish (smooth finish)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  i: [
    'Cable Size',
    'Number of Strands',
    'Insulation thickness(Minimum Insulation Thickness (mm))',
    'Conductor Diameter (Approx. Diameter (mm))',
    'Core Diameter (mm)',
    'Bundle Diameter(Approx. Overall Diameter (mm))',
    'Neutral Messenger Design(Multi Strand Round)',
    'Phase Identification(Phase Markings)',
    'Insulation Material (XLPE)',
    'Cable Construction (Multi-Strand)',
    'When delivered to the site, cable ends should have cups',
    "The outer sheath shouldn't have any damage",
    "The delivery drum shouldn't be damaged",
    'The cable should have markers showing (Its rating, year of manufacture and size)',
    'Conductor Material (Should be Aluminium)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  j: [
    'End cap Size (Tightly fitting and suitable for use on 6- 35mm2)',
    'End cap Material (Soft rubber)',
    'Colour (black)',
    'End cap design (Cone shaped), (b) Inner diameter designed in a such way that it tightly fits on individual conductors of6- 35mm2) (c Outer diameter designed in a such way that it tightly fits on tapping side of IPC of 6- 35mm2)'
  ],
  k: [
    'Clamp Size (state)',
    'Clamp Material (Aluminium or hard thermoplastic material)',
    'Design or Construction (Undetached fittings eg wedges)',
    'Gripping mechanism ( Use Wedge made out of thermoplastic material)',
    'Gripping ability (Able to grip appropriate conductor size without slip or release of conductor)',
    'Protection against corrosion of ferrous parts (Hot dip galvanised)',
    'Finish (Smooth and uniform thickness without any sharp edges and signs of corrosion)',
    'Test certificates (Routine, type tests) (provide)'
  ],
  l: [
    'Clamp Size (state)',
    ' Clamp  Material (Aluminium or hard thermoplastic material)',
    'Design or Construction (Undetached fittings eg wedges)',
    'Gripping mechanism(Able to grip appropriate conductor size without slip or release of conductor)',
    'Protection against corrosion of ferrous parts (Hot dip galvanised)',
    'Finish (Smooth and uniform thickness without any sharp edges and signs of corrosion)',
    'Test certificates (Routine, type tests)'
  ],
  m: [
    ' Clamp  Material ( Hard thermoplastic material)',
    'Design or Construction (Has a groove with a grip lever):(Has a body and mobile link or mobile neck):(Has a hole to allow easy attachment to the suspension hook)',
    'Clamping mechanism (Has a groove with a grip lever)',
    'Clamping ability (Able to clamp insulated neutral conductor size 54.6mm2 without slippage)',
    'Protection against UV radiation (Body and mobile link coated with a heat and UV radiant resistant)',
    'Finish (Smooth and uniform thickness without any sharp edges and signs of corrosion)',
    'Test certificates (Routine, type tests) (Smooth and uniform thickness without any sharp edges and signs of corrosion)'
  ],
  n: [
    'Adjustable Spanner Size',
    'Adjustable Spanner Material (Heat treated high grade steel)',
    'Thumb Screw Movement (Left hand)',
    'Jaw Scale (mm) (Precision marked scale)',
    'Handle (soft insulated grip)',
    'Finishing (Bright polished Nicel chrome finish)',
    'Maximum jaw opening (should open easyly to maximum)',
    'Adjusting Mechanism (knurl), Weight (kg)',
    'Test certificates (Routine, type test, National accrediation of supplier)'
  ],
  o: [
    'Nominal system Voltage ',
    'Rated current (400A)',
    'Moving blade material (tinned copper)',
    'Fixed Contact material (tinned copper)',
    'Insulator Material (Silicon Rubber /polymeric)',
    'Minimum phase to phase distance (450mm)',
    'Minimum isolating distance (confirm)',
    'Rod Insulator Material (polymeric)',
    'Insulator Minimum Creepage distance',
    'widith of H(2) pole center to center(mm)',
    'Connector operation (Ganged three phase Switch disconnector)',
    'Operation handle finish (Galvanised steel)',
    'Handle lock mechanism (0n/off position spring loaded)',
    "The cross arm body shouldn't have any damage (confirm)",
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  p: [
    'Operating Voltage (11kV and 33kV) ',
    'Control cabinet/panel and cable',
    'Control cabinet/panel (Adequately sealed, hot dip galvanised with provision of earthing point)',
    'Cable (Robust, multipin with weather proof connector)',
    'Lifting lugs (Minimum of two closed lifting lugs)',
    'Bushings (Should not be cracked with provision for terminating dropper conductors)',
    'Bushing material (Cyclo aliphatic epoxy resin/polymeric)',
    "Auto recloser Body Finish (Paint shouldn't Peel off and no signs of rust)",
    'Auto recloser Mounting brackets (Suitable Mounting Brackests accessories should be provided)',
    'Coating Auto recloser Mounting brackets (Hot dip galvanised)',
    'Eartrhing Terminals ( Earthing Terminals provided with bolt)',
    'Surge Arrester supports (Pre- Installed on Auto recloser body)',
    'Auto recloser Sealing and Bolting (Sealed with a gaskate and sufficiently close tightened bolts and nuts)',
    'Name Plate (Fitted with a Stainless steel rating plate)',
    'Bush Terminal markings for phase identification (Incoming and Outgoing terminal markings plainly and indelibly marked on the auto recloser)',
    'Close and Open manual operated button (Robust with ON/OFF indication)',
    'Insulation resistance measurements',
    'Test certificates (Routine, type tests, National accreditation of supplier) and schematic wiring diagram'
  ],
  q: [
    'Bolt Size',
    'Material (Hot Dip Galvanised Steel)',
    'Bolt and Nut Manufacture (Drop Forged Manufacture)',
    'Length of Bolt(mm)',
    'Length of Threaded Part on Bolt Body (mm)',
    'Diameter of Unthreaded Part(mm)',
    'Width of Nut (inch)',
    'Washers Assembled',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  r: [
    'Bolt Cutters Size',
    'Material of the cutting Jaws (All-purpose, center-cut jaws for soft, medium, and hard metals)',
    'Material of the handles (Drop-forged steel with insulation)',
    'Safety stops (shall be able to prevent trapping fingers)',
    'Lockplate renforcment (shall be able to prevent jaw bolts from loosening or turning & keeping jaws in correct alignment)',
    'Condition of the cutting jaws (not damaged & when closd light should not be seen through it)',
    'Maximum cutting capacity (Hard material)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  s: [
    'Blade  Size (17 to 30)',
    'Blade material (Hardened steel)',
    'Type of toothing (Peg/Raker tooth)',
    "Blade and teeth shouldn't be damaged",
    'Theeth per inch (Four for Raker,Three for Peg)',
    'Blade legth (As per the size)',
    'Number of blades in a sleeve (One per sleeve)',
    'Blade Coating (Rust resistant)',
    'Blade design (Hardened teeth  for long life &durability)',
    'Number of holes and hole diameter (4 Holes D6.60mm)',
    'Thickness of blade',
    'Sleeve marked showing;Blade size,brand name,manufacturer',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  t: [
    'Rated voltage(kV) (11 & 33KV)',
    'Material of cable bracket (steel)',
    'Method of preventing rusting of steel parts (Hot dip galvanised)',
    'Cable bracket insulators (Rated 11kv & 33KV)',
    'Creepage distance of insulators',
    '11kV Cable bracket (≥480mm)',
    '33kV Cable bracket (≥900mm)',
    'Finishing (Smooth and as free from spangle as possible)',
    'Dimensions',
    '11kV Cable bracket ( distance between phase to phase termination points≥ 310mm) (Distance between phase termination point and the lower mounting point≥650mm)',
    '33kV Cable bracket ( distance between phase to phase termination points≥ 480mm):(Distance between phase termination point and the lower mounting point≥800mm)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  u: [
    'Cable saddle Size (mm)',
    'Cable saddle design (Single, Double, Trefoil)',
    'Cable saddle materia (33% glass fiber reinforced polyamide resin)',
    'Cable saddle colour (Carbon black ultraviolet light absorber)',
    'Cable saddle hole diameter (mm)',
    "Cable saddle Finish (Shouldn't be damaged)",
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  v: [
    'System Highest Voltages (11kV)',
    'Material Design (Heat Shrinkable Material)',
    'Cable Joints Design (Filled Type (Provided with a core separator and filler mastics)',
    'Cable termination tail length (3 core cables) (650(indoor)/1000(outdoor)',
    'Cable termination tail length (1 core cables)550(indoor&outdoor)',
    'Accessories (Construction and method of assembly)',
    'Manuals (Support Documentation) Construction and method of assembly',
    'Markings (Manufacturers Identification mark, Expiry date and a part number)',
    'Parkaging (Strong cardboard container to protect it from mechanical damage, Individual parts shall be packed in strong sealed plastic bags)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  w: [
    'Cable Tie Material (Nylon)',
    'Cable Tie Color (Black)',
    'Cable Tie Dimensions (Length ≥ 100, W ≥  2.5)',
    'Packaging (Water Tight Bags)',
    'Tensile Strength (Kgs) (8 to 22)',
    'Type (Self-Locking)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  x: [
    'Climbers Adjustable (1/4 Inch increments)',
    'Broad stirrup (113mm wide)',
    'Cushioned High-grade leather climber pads',
    'Climber straps material (Nylon)',
    'Steel sleeve (Secured by 2 slotted hex-head bolts and washers)',
    'Ankle strap security (Split ring)',
    'Foot rest material (steel alloy)',
    'Finishing (Rust resistant coarting)',
    'Gaff material(Steel alloy)',
    'Left and right indication',
    'Attachment to safty shoes/construction design (By straps)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  y: [
    'Size of communication cable connector (0.7sq.mm)',
    'Circuit board present and connections firm',
    'Material of circuit board housing (Hard plastic)',
    'Dimensions of circuit board housing (state)',
    'Method of preventing rusting of steel parts (Hot dip galvanised)',
    'Finishing (Smooth and as free from spangle as possible)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  z: [
    'Material (PVC (Polyvinyl chloride))',
    'Colour (white)',
    'Clip brand (tower)',
    'Clip diameter (6-9mm)',
    'Clip nail (Pre-Installed Steel Galvanised fastener Nail)',
    'Packaging (boxes/polythene bags',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  aa: [
    'Pole Type (Spun moulded)',
    'Pole shape (Round or I-shape)',
    'Pole length(m) (10,12,14 & 16)',
    'Pole top diameters(mm)- minimum (190 for 10m 12m & 14m and 230 for 16m)',
    'Pole butt diameters(mm)-minimum (330 for 10m,350 for 12m ,377 for 14m and 404 for 16m)',
    'Strength class (C25 for10m  & C50 for12m, 14m,16m)',
    'Ultimate load for C50(kN) - minimum (6.0 for 12m,  8.00 for 14m, 8.55 for 16m)',
    ,
    'Reinforcement(mm)(7)',
    'Average thickness of the butt(mm) (55)',
    'Pole taper for each pole(mm per meter) (13)',
    'Danger sign (installed)',
    'cement used',
    'pole markings (provided)',
    'pole finish',
    'strength test report',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  ab: [
    'Conductor Size',
    'No. of strands and strand diameter - Al.(mm)',
    'Material used (AAAC/ACSR /Steel Core/Galvanized Steel)',
    'Strand and wire diameter-steel (mm)',
    'Approximate overall diameter (Approx. Diameter (mm)',
    'Approximate mass (kg/km)',
    'Approximate tensile strength (kn)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  ac: [
    'Width (2.8/71.12mm)',
    'Chuck Size ( 1/4 in Hex)',
    'Max Drilling Diameter (6mm/10mm-Steel,Wood & Walls)',
    'Drilling Bits (6mm/10mm drilling bits for Steel, Wood&Walls)',
    'Chuck Design (keyless)',
    'Case Type (Bag/Plastic Casing)',
    'Accessories (2- 18V Lithium-Ion FatPack Batteries, 1 - 45-Minute Lithium-ion Battery Fast Charger & 1 - Carrying Case)',
    'Battery Type (Lizthium ion',
    'Battery voltage (18V)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  ad: [
    'Design Construction of  Hammer stapler (All stainless steel construction)',
    'Handle Should be soft grip',
    'Performance (Strong penetrating power and quick excellent performance)',
    'Head Rotational Angle (fixed)',
    'Working Condition (Multiple application)',
    'Staples (Stainless steel.- Galvanized)',
    'Staple  size  140 T50 (6 - 12 mm)',
    'Weight of Tool (light & versatile',
    'Accessories (Full range of approved  staples)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  ae: [
    'CT Rating (200/5A,400/5A,800/5A)',
    'Voltage rating (415± 6%V)',
    'Design or Construction (Ring type core with engineered plastic material)',
    'Internal diameter of ring (200/5A ; 45mm,400/5A;70mm,800/5A; 80mm)',
    'Polarities (Permanently marked on the CT)',
    'CT Steel parts (Hot dip galvanised)',
    'Secondary terminals of CT (Housed in a terminal box with options for sealing)',
    'Material for terminal box (Transparent hard plastic)',
    'Mounting (CT should have steel foot stand with mounting holes 6mm diameter)',
    'Packing Packed in cardboard boxes',
    'Name of manufacturer',
    'Serial number',
    'Rated primary and secondary current',
    'Accuracy Class, Rated Burden & instrument security factor',
    'Rated Insulation Level',
    'Insulation Class',
    'Rated Short-time current/duration & Dynamic peak current',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  af: [
    'Sheet Material (Mild Steel HDG sheet)',
    'Sheet Finish (Vitreous Enameled)',
    'Paint Composition (High Gloss Baked Enamel Finish)',
    'Letterings (RED with a White Enameled Background)',
    'Wording Printing Screen Printed',
    'Dimensions of Danger Sign Plate ((280 x210 x1.5mm)',
    'Number and Diameter of holes for Nailing (4 Holes of D10mm each)',
    'Corner Finishing (Rounded Off smoothly and Blunt)',
    'Wording Languages (Luganda, English and Swahili)',
    'Markings',
    'Test Certificates and Type Test Reports'
  ],
  ag: [
    'DIN Rail Material (Galvanized Cold Rolled Carbon Steel)',
    'DIN Rail Dimension ((35x7.5 x1.0)mm)',
    'DIN Rail Length (100mm)',
    'Mounting Holes/Slots (Wood Screw Holes/Slots)',
    'Diameter of Mounting Holes (7mm)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  ah: [
    'Material (Hot Dip Galvanised Steel)',
    'D-Iron Manufacture (Drop Forged Manufacture)',
    'Thickness of D-Iron Body (mm)',
    'Width of D-Iron Body (mm)',
    'Approxmate Over Length of D-Iron (330mm)',
    'Number and Diameter of Holes (3 of D18mm)',
    'D-Iron Finish (Smooth Galvanised Finish)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  ai: [
    'Transformer Rating',
    'Operating Voltage (11kv & 33Kv)',
    'Vector group (three phase):(Dyn 11)',
    'Cooling type (ONAN)',
    'Transformer Type (Completely Self Protected)',
    'Lifting lugs (Minimum of two closed lifting lugs)',
    'Bushings (Should not be cracked)',
    'Transformer Body (No oil Leakage)',
    "Transformer Body Finish (Paint shouldn't Peel off and no signs of rust)",
    'Mounting (Mounting Brackests accessories should be provided)',
    'Eartrhing Terminals (Multiple Earthing Terminals should be provided)',
    'Surge Arresters (Pre- Installed on the Transformer, arresters shall be fitted with arcing horns)',
    'Surge Arresters Crossectional area (16sqmm)',
    'Transformer Sealing and Bolting (Sealed with a gaskate and sufficiently close tightened bolts and nuts)',
    'Name Plate (Fitted with a Stainless steel rating plate)',
    'Bush Terminal markings (Primary and Secondary terminal markings plainly and indelibly marked on the transformer)',
    'Number of steps/Tapping Positions (5)',
    'LV Bushing Creepage Distance (≥40mm)',
    'MV Bushing Creepage Distance (≥300mm)',
    'MV Bushing Creepage Distance (≥900mm)',
    'Current Transformer Construction (Pre- Installed in the Transformer LV Distribution box)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  aj: [
    'System Voltage',
    'Rated current (400A)',
    'Creepage distance',
    "Insulation Material (Polymeric and Shouldn't have any Damage)",
    'Mounting Accessories and Brackets',
    'Accessories Construction (Hot Deep Galv. Steel)',
    'Fusant (Correct rating Provided)',
    'Operation (Easily Operational with Stick.)',
    'Dimensions (Per Technical Drawing)',
    'Markings',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  ak: [
    'Earth rod Material (Copper cladded steel)',
    'Thickness of copper cladding (0.25mm minimum)',
    'Construction (Tappered portion, threaded portion with a tip)',
    'Dimensions (D-13mm)',
    'Length of copper earth rod (1.4-1.5m',
    'Length of tip (10-12mm',
    'Length of threaded portion (40-50mm',
    'Type of threading (Isometric type)',
    'Earth rod clamp (3mm thick',
    'Clamp material (tinned copper)',
    'Length of clamp (40-50mm)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  al: [
    'Mode of Construction (Forged in one piece and fully Polished)',
    'Material (All Steel Metal)',
    'Construction Style (Curved head with Long straight claws)',
    'Grip Material (Fiberglass or Nylon Vinyl deep cusion grip)',
    'Overall Length (31.8cm (12.5)',
    'Finish (Handle and Head are fully Polished)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  am: [
    'Eye Bolt Size',
    'Material (Hot Dip Galvanised Steel)',
    'Eye Bolt Manufacture (Drop Forged Manufacture)',
    'Length of eye bolt(mm)',
    'Length of threads(mm)',
    'Diameter of unthreaded part(mm)',
    'Diameter of Eye Bolt(mm)',
    'Nuts and Washers',
    'Thickness of Eye (mm)',
    'Length of Threaded part',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  an: [
    'Sheet metal thickness including coating (1.6mm)',
    'Material (mild steel plate)',
    'Door hinges construction (Door hinges concealed)',
    'Meter box colour (UMEME green)',
    'Transparent  glass hole dimesions (300mm long and 30mm wide (LxW)',
    'Transparent glass thickness (6mm)',
    'Thickness of internal wooden board (18mm)',
    'Dimensions of internal wooden board (Length (L) =490mm, Height (H) =520mm, Width (W) = 18mm)',
    'Number of Holes for incoming and outgoing cable (02)',
    'Diameter of holes for cable entry (50mm)',
    'Meter box louver construction (3 or 4 louvres of length 90mm, on both sides of the box  tapering down)',
    'Earthing Terminal bolt (35 x 9 mm made of galvanized iron earth with a washer)',
    'Locking system (A lock that only accommodates a standard padlock  and is not easy to tamper with. It shall be easy to  operate and lock):(The locking hole should be at a distance of 2mm from the door)',
    'The Meter Box body condition (Should not have any damages)',
    'Height of support stands (860mm)',
    'External dimensions of the box (Height (H) =600mm, Length (L) = 570mm)'
  ],
  ao: [
    'Parts of the Device',
    'Body Belt Material',
    'Body Belt Design',
    'Body Belt Stitching',
    'Material of Distribution Strap',
    'Stopping Cleat',
    'Labels',
    'Fixed Dual Slot D-Ring',
    'Labels',
    'Cynch-Lok Roller Adjuster (Strap)',
    'Fixed Dual Slot D-Ring (Strap)',
    'Accessories',
    'Manuals',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  ap: [
    'Operating Voltage ( LV; ≤ 1000V)',
    'Feeder pillar body',
    'Lifting lugs',
    'Feeder pillar Body Finish',
    'Feeder pillar bus bars(Ammeter of accuracy at least +/- 2.5%.,installed):(Voltmeter of accuracy at least at least +/-1.5%.)',
    'Coating Auto recloser Mounting brackets',
    'Eartrhing Terminals',
    ' One incomer and four or six or eight outgoing fused circuts (each three phase)',
    'Three current transformers ratio 1600/800/5, class 1.0 10VA',
    'Name Plate(Fitted with a Stainless steel rating plate)',
    ' Circuit identification/labelling facility',
    'Dimensions of feeder pillar',
    'The top cover of Feeder pillar shall have inclined surface(s) to avoid Accumulation of rain water. It shall have a canopy over the door',
    'MV Bushing Creepage Distance',
    ' 13A 3-pin switch socket outlet with plug (square pins)',
    'Ventilation louvres with anti-vermin baffles',
    'Phase barries  provided to prevent insertion of fuse links between contacts of different phases. The barrier shall be of material which does not readily support combustion',
    '3 phase 4-wire fuse unit',
    'Test certificates (Routine, type tests, National accreditation of supplier) and schematic wiring diagram'
  ]
};

export default paramData;
