const paramData = {
  a: [
    'External enclosure status',
    'Antenna cover',
    'Box labels',
    'Hinges',
    'Locking mechanism',
    'Vents and mesh',
    'Doors',
    'Door sensors',
    'Meter(confirm Modem)',
    'Circuit Breaker',
    'Cable Jumpers',
    'Termination screws',
    'Termination Safety covers',
    'Termination separators',
    'Earth loops',
    'Earthing point',
    'Knock - out plates',
    'AC - DC converter',
    'CIU',
    'Cross arm (2pcs)',
    'Brackets (2pcs)',
    'L - mounting plate (4 pcs)',
    '3/4 by 2 bolts (12pcs)',
    '3/4 by 12 bolts (4pcs)',
    'Flat round washers (32pcs)'
  ],
  b: [
    'Design Construction of  Hammer stapler	(All stainless steel construction)',
    'Handle (Should be soft grip)',
    'Performance (Strong penetrating power and quick excellent performance)',
    'Head Rotational Angle (Fixed)',
    'Working Condition (Multiple application)',
    'Staples (Stainless steel.- Galvanized)',
    'Staple  size  140 T50 (6 - 12 mm)',
    'Weight of Tool (light and versatile)',
    'Accessories (Full range of approved staples)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  c: [
    'End cap Size (state)',
    ' End cap  Material (UV stabilized insulation rubber)',
    'Design or Construction (Suitably designed for sealing the open ends of insulated conductors against water ingress)',
    'Installation (Can be held in installed position by elastic forces)',
    'Finish (Smooth and uniform thickness without any sharp edges)',
    'Test certificates (Routine, type tests)  provide'
  ],
  d: [
    'Material (Nylon/Polyester)',
    'Design (Factory spliced Eyes at both ends)',
    'Rope Diameter (0.5)',
    'Type (Double braided inner core with extra braided outer jacket)',
    'Colour (White with green tracer/Yellow)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  e: [
    'Material of the Box (Hard Plastic)',
    'External  enclosure appearance (Should be smooth with no damage)',
    'Bottom holes (4 holes D-22mm)',
    'Neutral Block-Pre installed (confirm)',
    'Dimensions of the box (L=310mm,W=110mm,H=118mm)',
    'Check for accessories to be provided (confirm)',
    'Current rating of the box 80-100A (confirm)',
    'Hinghes Opening with ease(confirm)',
    'Test certificate to be provided(confirm)'
  ],
  f: [
    'Material(Nylon/Polyester)',
    'Design (Factory spliced Eyes at both ends)',
    'Rope Diameter (1)',
    'Type (Double braided inner core with extra braided outer jacket)',
    'Colour (White with green tracer)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  g: [
    'Material (Aluminium/Glass fiber)',
    'Length (5.7m(18.6ft)',
    'Step Distance (28cm)',
    'Features (Work platform and Step Platform)',
    'Construction (Has Stabilizer Rubbers and can be turned into step/straight ladder)',
    'Finish (smooth finish)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  h: [
    'Material of Tape (Fibreglass covered with synthetic material)',
    'Material and Construction of Casing (Synthetic casing with tape-retraction winder handle.)',
    'Casing Finish (Vinyl-Coated Steel Casing)',
    'Length (50m)',
    'Band Width (12mm-13mm)',
    'Colour (Green/Blue, Black/White)',
    'Units of Measurement (Metric and Imperial)',
    'Finish (smooth finish)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  i: [
    'Cable Size (35mm²),(70mm²),(95mm²),(120mm²),(150mm²),(Neutral Messenger 54.6mm²)',
    'Number of Strands (7),(19),(19),(19),(30),(7)',
    'Insulation thickness(Minimum Insulation Thickness (mm)(1.3),(1.5),(1.7),(1.8),(1.8),(1.34))',
    'Conductor Diameter (Approx. Diameter (mm) (6.6),(9.3),(11),(12.5),(13.9),(9.2))',
    'Core Diameter (mm)(11),(14),(16.1),(17.6),(18.8),(9.2)',
    'Bundle Diameter(Approx. Overall Diameter (mm),(25),(32),(37),(40),(44),(30))',
    'Neutral Messenger Design(Multi Strand Round)',
    'Phase Identification(Phase Markings)',
    'Insulation Material (XLPE)',
    'Cable Construction (Multi-Strand)',
    'When delivered to the site, cable ends should have cups',
    "The outer sheath shouldn't have any damage",
    "The delivery drum shouldn't be damaged",
    'The cable should have markers showing (Its rating, year of manufacture and size)',
    'Conductor Material (Should be Aluminium)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  j: [
    'End cap Size (Tightly fitting and suitable for use on 6- 35mm2)',
    'End cap Material (Soft rubber)',
    'Colour (black)',
    'End cap design (Cone shaped), (b) Inner diameter designed in a such way that it tightly fits on individual conductors of6- 35mm2) (c Outer diameter designed in a such way that it tightly fits on tapping side of IPC of 6- 35mm2)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  k: [
    'Clamp Size (state)',
    'Clamp Material (Aluminium or hard thermoplastic material)',
    'Design or Construction (Undetached fittings eg wedges)',
    'Gripping mechanism ( Use Wedge made out of thermoplastic material)',
    'Gripping ability (Able to grip appropriate conductor size without slip or release of conductor)',
    'Protection against corrosion of ferrous parts (Hot dip galvanised)',
    'Finish (Smooth and uniform thickness without any sharp edges and signs of corrosion)',
    'Test certificates (Routine, type tests) (provide)'
  ],
  l: [
    'Clamp Size (state)',
    ' Clamp  Material (Aluminium or hard thermoplastic material)',
    'Design or Construction (Undetached fittings eg wedges)',
    'Gripping mechanism(Able to grip appropriate conductor size without slip or release of conductor)',
    'Protection against corrosion of ferrous parts (Hot dip galvanised)',
    'Finish (Smooth and uniform thickness without any sharp edges and signs of corrosion)',
    'Test certificates (Routine, type tests)'
  ],
  m: [
    ' Clamp  Material ( Hard thermoplastic material)',
    'Design or Construction (Has a groove with a grip lever):(Has a body and mobile link or mobile neck):(Has a hole to allow easy attachment to the suspension hook)',
    'Clamping mechanism (Has a groove with a grip lever)',
    'Clamping ability (Able to clamp insulated neutral conductor size 54.6mm2 without slippage)',
    'Protection against UV radiation (Body and mobile link coated with a heat and UV radiant resistant)',
    'Finish (Smooth and uniform thickness without any sharp edges and signs of corrosion)',
    'Test certificates (Routine, type tests) (Smooth and uniform thickness without any sharp edges and signs of corrosion)'
  ],
  n: [
    'Adjustable Spanner Size (8),(10),(12)',
    'Adjustable Spanner Material (Heat treated high grade steel)',
    'Thumb Screw Movement (Left hand)',
    'Jaw Scale (mm) (Precision marked scale)',
    'Handle (soft insulated grip)',
    'Finishing (Bright polished Nicel chrome finish)',
    'Maximum jaw opening (should open easyly to maximum) (≥25mm),(≥30mm),(≥43mm)',
    'Adjusting Mechanism (knurl)',
    'Weight (kg) (≤ 0.269),(≤ 0.635),(≤ 1.025)',
    'Test certificates (Routine, type test, National accrediation of supplier)'
  ],
  o: [
    'Nominal system Voltage ',
    'Rated current (400A)',
    'Moving blade material (tinned copper)',
    'Fixed Contact material (tinned copper)',
    'Insulator Material (Silicon Rubber /polymeric)',
    'Minimum phase to phase distance (450mm) (430mm)',
    'Minimum isolating distance (confirm)',
    'Rod Insulator Material (polymeric)',
    'Insulator Minimum Creepage distance (900mm)',
    'widith of H(2) pole center to center(1200mm)',
    'Connector operation (Ganged three phase Switch disconnector)',
    'Operation handle finish (Galvanised steel)',
    'Handle lock mechanism (0n/off position spring loaded)',
    "The cross arm body shouldn't have any damage (confirm)",
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  p: [
    'Operating Voltage (11kV and 33kV) ',
    'Control cabinet/panel and cable',
    'Control cabinet/panel (Adequately sealed, hot dip galvanised with provision of earthing point)',
    'Cable (Robust, multipin with weather proof connector)',
    'Lifting lugs (Minimum of two closed lifting lugs)',
    'Bushings (Should not be cracked with provision for terminating dropper conductors)',
    'Bushing material (Cyclo aliphatic epoxy resin/polymeric)',
    "Auto recloser Body Finish (Paint shouldn't Peel off and no signs of rust)",
    'Auto recloser Mounting brackets (Suitable Mounting Brackests accessories should be provided)',
    'Coating Auto recloser Mounting brackets (Hot dip galvanised)',
    'Eartrhing Terminals ( Earthing Terminals provided with bolt)',
    'Surge Arrester supports (Pre- Installed on Auto recloser body)',
    'Auto recloser Sealing and Bolting (Sealed with a gaskate and sufficiently close tightened bolts and nuts)',
    'Name Plate (Fitted with a Stainless steel rating plate)',
    'Bush Terminal markings for phase identification (Incoming and Outgoing terminal markings plainly and indelibly marked on the auto recloser)',
    'Close and Open manual operated button (Robust with ON/OFF indication)',
    'Insulation resistance measurements',
    'Test certificates (Routine, type tests, National accreditation of supplier) and schematic wiring diagram'
  ],
  q: [
    'Bolt Size (5/8” X 12”),(5/8” X 4.5”),(3/4” X 12”),(3/4” X 2”),(Eye bolt and nut 3/4” X 14”),(Eye nut 3/4),(Pig tail hook)',
    'Material (Hot Dip Galvanised Steel)',
    'Bolt and Nut Manufacture (Drop Forged Manufacture)',
    'Length of Bolt(mm) (12/300mm),(4.5/112mm),(50mm/2),(240)',
    'Length of Threaded Part on Bolt Body (mm) (2.2/55mm),(6/150mm),(46mm/1.8),(150mm)',
    'Diameter of Unthreaded Part(mm),(15.3),(15.3),(19.16),(16)',
    'Width of Nut (inch) (5/8),(3/4)',
    'Washers Assembled',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  r: [
    'Bolt Cutters Size (18(457mm)),(36(914mm))',
    'Material of the cutting Jaws (All-purpose, center-cut jaws for soft, medium, and hard metals)',
    'Material of the handles (Drop-forged steel with insulation)',
    'Safety stops (shall be able to prevent trapping fingers)',
    'Lockplate renforcment (shall be able to prevent jaw bolts from loosening or turning & keeping jaws in correct alignment)',
    'Condition of the cutting jaws (not damaged & when closd light should not be seen through it)',
    'Maximum cutting capacity (Hard material) (6mm),(11mm)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  s: [
    'Blade  Size (17 to 30)',
    'Blade material (Hardened steel)',
    'Type of toothing (Peg/Raker tooth)',
    "Blade and teeth shouldn't be damaged",
    'Theeth per inch (Four for Raker,Three for Peg)',
    'Blade legth (As per the size)',
    'Number of blades in a sleeve (One per sleeve)',
    'Blade Coating (Rust resistant)',
    'Blade design (Hardened teeth  for long life &durability)',
    'Number of holes and hole diameter (4 Holes D6.60mm)',
    'Thickness of blade (1.2mm)',
    'Sleeve marked showing;Blade size,brand name,manufacturer',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  t: [
    'Rated voltage(kV) (11 & 33KV)',
    'Material of cable bracket (steel)',
    'Method of preventing rusting of steel parts (Hot dip galvanised)',
    'Cable bracket insulators (Rated 11kv & 33KV)',
    'Creepage distance of insulators',
    '11kV Cable bracket (≥480mm)',
    '33kV Cable bracket (≥900mm)',
    'Finishing (Smooth and as free from spangle as possible)',
    'Dimensions',
    '11kV Cable bracket ( distance between phase to phase termination points≥ 310mm) (Distance between phase termination point and the lower mounting point≥650mm)',
    '33kV Cable bracket ( distance between phase to phase termination points≥ 480mm):(Distance between phase termination point and the lower mounting point≥800mm)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  u: [
    'Cable saddle Size (mm)',
    'Cable saddle design (Single, Double, Trefoil (26-38),(38-50),(50-60),(60-70),(70-80),(80-90))',
    'Cable saddle materia (33% glass fiber reinforced polyamide resin) (≥56.0),(≥73.0),(≥78.0)',
    'Cable saddle colour (Carbon black ultraviolet light absorber) (≥10.8),(≥16.0),(≥17.1) ',
    'Cable saddle hole diameter (mm) (≥20)',
    "Cable saddle Finish (Shouldn't be damaged)",
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  v: [
    'System Highest Voltages (11kV)',
    'Material Design (Heat Shrinkable Material)',
    'Cable Joints Design (Filled Type (Provided with a core separator and filler mastics)',
    'Cable termination tail length (3 core cables) (650(indoor)/1000(outdoor)',
    'Cable termination tail length (1 core cables)550(indoor&outdoor)',
    'Accessories (Construction and method of assembly), (Complete with all component)',
    'Manuals (Support Documentation) Construction and method of assembly',
    'Markings (Manufacturers Identification mark, Expiry date and a part number)',
    'Parkaging (Strong cardboard container to protect it from mechanical damage, Individual parts shall be packed in strong sealed plastic bags)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  w: [
    'Cable Tie Material (Nylon)',
    'Cable Tie Color (Black)',
    'Cable Tie Dimensions (Length ≥ 100, W ≥  2.5)',
    'Packaging (Water Tight Bags)',
    'Tensile Strength (Kgs) (8 to 22)',
    'Type (Self-Locking)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  x: [
    'Climbers Adjustable (1/4 Inch increments)',
    'Broad stirrup (113mm wide)',
    'Cushioned High-grade leather climber pads',
    'Climber straps material (Nylon)',
    'Steel sleeve (Secured by 2 slotted hex-head bolts and washers)',
    'Ankle strap security (Split ring)',
    'Foot rest material (steel alloy)',
    'Finishing (Rust resistant coarting)',
    'Gaff material(Steel alloy)',
    'Left and right indication',
    'Attachment to safty shoes/construction design (By straps)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  y: [
    'Size of communication cable connector (0.7sq.mm)',
    'Circuit board present and connections firm',
    'Material of circuit board housing (Hard plastic)',
    'Dimensions of circuit board housing (state)',
    'Method of preventing rusting of steel parts (Hot dip galvanised)',
    'Finishing (Smooth and as free from spangle as possible)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  z: [
    'Material (PVC (Polyvinyl chloride))',
    'Colour (white)',
    'Clip brand (tower)',
    'Clip diameter (6-9mm)',
    'Clip nail (Pre-Installed Steel Galvanised fastener Nail)',
    'Packaging (boxes/polythene bags',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  aa: [
    'Pole Type (Spun moulded)',
    'Pole shape (Round or I-shape)',
    'Pole length(m) (10,12,14 & 16)',
    'Pole top diameters(mm)- minimum (190 for 10m 12m & 14m and 230 for 16m)',
    'Pole butt diameters(mm)-minimum (330 for 10m,350 for 12m ,377 for 14m and 404 for 16m)',
    'Strength class (C25 for10m  & C50 for12m, 14m,16m)',
    'Ultimate load for C50(kN) - minimum (6.0 for 12m,  8.00 for 14m, 8.55 for 16m)',
    'Reinforcement(mm)(7)',
    'Average thickness of the butt(mm) (55)',
    'Pole taper for each pole(mm per meter) (13)',
    'Danger sign (installed)',
    'cement used',
    'pole markings (provided)',
    'pole finish',
    'strength test report',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  ab: [
    'Conductor Size (50mm²),(100mm²),(150mm²),(200mm²),(3/0.102mm²),(7/8swg),(7/12swg)',
    'No. of strands and strand diameter - Al.(mm) (6/3.35),(6/4.72),(18/3.35),(19/3.51),(19/3.93),(3/2.64±0.5),(7/4±0.5),(7/2.5±0.5)',
    'Material used (AAAC/ACSR /Steel Core/Galvanized Steel)',
    'Strand and wire diameter-steel (mm) (1/3.35),(7/1.57)',
    'Approximate overall diameter (Approx. Diameter (mm) (10.05),(14.15),(16.75),(17.6),(19.6),(5.56),(12),(7.5)',
    'Approximate mass (kg/km)(214),(394),(506),(506.1),(632.7),(131),(717),(308)',
    'Approximate tensile strength (kn) (18.35),(32.7),(35.7),(54.32),(67.91),(21.796),(101),(44.4)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  ac: [
    'Width (2.8/71.12mm)',
    'Chuck Size ( 1/4 in Hex)',
    'Max Drilling Diameter (6mm/10mm-Steel,Wood & Walls)',
    'Drilling Bits (6mm/10mm drilling bits for Steel, Wood&Walls)',
    'Chuck Design (keyless)',
    'Case Type (Bag/Plastic Casing)',
    'Accessories (2- 18V Lithium-Ion FatPack Batteries, 1 - 45-Minute Lithium-ion Battery Fast Charger & 1 - Carrying Case)',
    'Battery Type (Lizthium ion)',
    'Battery voltage (18V)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  ad: [
    'Design Construction of  Hammer stapler (All stainless steel construction)',
    'Handle Should be soft grip',
    'Performance (Strong penetrating power and quick excellent performance)',
    'Head Rotational Angle (fixed)',
    'Working Condition (Multiple application)',
    'Staples (Stainless steel.- Galvanized)',
    'Staple  size  140 T50 (6 - 12 mm)',
    'Weight of Tool (light & versatile',
    'Accessories (Full range of approved  staples)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  ae: [
    'CT Rating (200/5A,400/5A,800/5A)',
    'Voltage rating (415± 6%V)',
    'Design or Construction (Ring type core with engineered plastic material)',
    'Internal diameter of ring (200/5A ; 45mm,400/5A;70mm,800/5A; 80mm)',
    'Polarities (Permanently marked on the CT)',
    'CT Steel parts (Hot dip galvanised)',
    'Secondary terminals of CT (Housed in a terminal box with options for sealing)',
    'Material for terminal box (Transparent hard plastic)',
    'Mounting (CT should have steel foot stand with mounting holes 6mm diameter)',
    'Packing Packed in cardboard boxes',
    'Name of manufacturer',
    'Serial number',
    'Rated primary and secondary current',
    'Accuracy Class, Rated Burden & instrument security factor',
    'Rated Insulation Level',
    'Insulation Class',
    'Rated Short-time current/duration & Dynamic peak current',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  af: [
    'Sheet Material (Mild Steel HDG sheet)',
    'Sheet Finish (Vitreous Enameled)',
    'Paint Composition (High Gloss Baked Enamel Finish)',
    'Letterings (RED with a White Enameled Background)',
    'Wording Printing Screen Printed',
    'Dimensions of Danger Sign Plate ((280 x210 x1.5mm)',
    'Number and Diameter of holes for Nailing (4 Holes of D10mm each)',
    'Corner Finishing (Rounded Off smoothly and Blunt)',
    'Wording Languages (Luganda, English and Swahili)',
    'Markings',
    'Test Certificates and Type Test Reports'
  ],
  ag: [
    'DIN Rail Material (Galvanized Cold Rolled Carbon Steel)',
    'DIN Rail Dimension ((35x7.5 x1.0)mm)',
    'DIN Rail Length (100mm)',
    'Mounting Holes/Slots (Wood Screw Holes/Slots)',
    'Diameter of Mounting Holes (7mm)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  ah: [
    'Material (Hot Dip Galvanised Steel)',
    'D-Iron Manufacture (Drop Forged Manufacture)',
    'Thickness of D-Iron Body (mm)',
    'Width of D-Iron Body (mm)',
    'Approxmate Over Length of D-Iron (330mm)',
    'Number and Diameter of Holes (3 of D18mm)',
    'D-Iron Finish (Smooth Galvanised Finish)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  ai: [
    'Transformer Rating (100KVA),(200KVA),(315KVA),(500KVA),(50KVA)',
    'Operating Voltage (11kv & 33Kv)',
    'Vector group (three phase):(Dyn 11)',
    'Cooling type (ONAN)',
    'Transformer Type (Completely Self Protected)',
    'Lifting lugs (Minimum of two closed lifting lugs)',
    'Bushings (Should not be cracked)',
    'Transformer Body (No oil Leakage)',
    "Transformer Body Finish (Paint shouldn't Peel off and no signs of rust)",
    'Mounting (Mounting Brackests accessories should be provided)',
    'Eartrhing Terminals (Multiple Earthing Terminals should be provided)',
    'Surge Arresters (Pre- Installed on the Transformer, arresters shall be fitted with arcing horns)',
    'Surge Arresters Crossectional area (16sqmm)',
    'Transformer Sealing and Bolting (Sealed with a gaskate and sufficiently close tightened bolts and nuts)',
    'Name Plate (Fitted with a Stainless steel rating plate)',
    'Bush Terminal markings (Primary and Secondary terminal markings plainly and indelibly marked on the transformer)',
    'Number of steps/Tapping Positions (5)',
    'LV Bushing Creepage Distance (≥40mm)',
    'MV Bushing Creepage Distance (≥300mm)',
    'MV Bushing Creepage Distance (≥900mm)',
    'Current Transformer Construction (Pre- Installed in the Transformer LV Distribution box)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  aj: [
    'System Voltage (11kV),(33Kv)',
    'Rated current (400A)',
    'Creepage distance',
    "Insulation Material (Polymeric and Shouldn't have any Damage)",
    'Mounting Accessories and Brackets',
    'Accessories Construction (Hot Deep Galv. Steel)',
    'Fusant (Correct rating Provided)',
    'Operation (Easily Operational with Stick.)',
    'Dimensions (Per Technical Drawing)',
    'Markings',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  ak: [
    'Earth rod Material (Copper cladded steel)',
    'Thickness of copper cladding (0.25mm minimum)',
    'Construction (Tappered portion, threaded portion with a tip)',
    'Dimensions (D-13mm)',
    'Length of copper earth rod (1.4-1.5m',
    'Length of tip (10-12mm',
    'Length of threaded portion (40-50mm',
    'Type of threading (Isometric type)',
    'Earth rod clamp (3mm thick',
    'Clamp material (tinned copper)',
    'Length of clamp (40-50mm)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  al: [
    'Mode of Construction (Forged in one piece and fully Polished)',
    'Material (All Steel Metal)',
    'Construction Style (Curved head with Long straight claws)',
    'Grip Material (Fiberglass or Nylon Vinyl deep cusion grip)',
    'Overall Length (31.8cm (12.5)',
    'Finish (Handle and Head are fully Polished)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  am: [
    'Eye Bolt Size (M16 (⅝),(M20 (¾))',
    'Material (Hot Dip Galvanised Steel)',
    'Eye Bolt Manufacture (Drop Forged Manufacture)',
    'Length of eye bolt(mm) (350(14))',
    'Length of threads(mm) (150(6))',
    'Diameter of unthreaded part(≥19.16mm)',
    'Diameter of Eye Bolt(mm)(40)',
    'Nuts and Washers',
    'Thickness of Eye (20mm)',
    'Length of Threaded part(150)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  an: [
    'Sheet metal thickness including coating (1.6mm)',
    'Material (mild steel plate)',
    'Door hinges construction (Door hinges concealed)',
    'Meter box colour (UMEME green)',
    'Transparent  glass hole dimesions (300mm long and 30mm wide (LxW)',
    'Transparent glass thickness (6mm)',
    'Thickness of internal wooden board (18mm)',
    'Dimensions of internal wooden board (Length (L) =490mm, Height (H) =520mm, Width (W) = 18mm)',
    'Number of Holes for incoming and outgoing cable (02)',
    'Diameter of holes for cable entry (50mm)',
    'Meter box louver construction (3 or 4 louvres of length 90mm, on both sides of the box  tapering down)',
    'Earthing Terminal bolt (35 x 9 mm made of galvanized iron earth with a washer)',
    'Locking system (A lock that only accommodates a standard padlock  and is not easy to tamper with. It shall be easy to  operate and lock):(The locking hole should be at a distance of 2mm from the door)',
    'The Meter Box body condition (Should not have any damages)',
    'Height of support stands (860mm)',
    'External dimensions of the box (Height (H) =600mm, Length (L) = 570mm)'
  ],
  ao: [
    'Parts of the Device (Adjustable Rope Lanyards(Blue&Yellow), Body Belt and Distribution Strap - (Four Componets))',
    'Body Belt Material (High Grade Leather)',
    'Body Belt Design (Cushioned for Comfort)',
    'Body Belt Stitching (High Grade Stitching on Body Belt and Rope Lanyards)',
    'Material of Distribution Strap (Neoprene Impregnated Nylon)',
    'Stopping Cleat (Cleat is mounted securely with no cracks, chips, or missing cleats)',
    'Labels (Verify labels are attached and legible)',
    'Fixed Dual Slot D-Ring (Verify the dual slot D-Ring is fi xed in place and there are no visible cracks or wear)',
    'Labels (Name / trademark of manufacturer, Applicable Standards,  Care and cleaning Instructions & Sizes.)',
    'Cynch-Lok Roller Adjuster (Strap)- (Verify the adjuster moves freely, locks the strap into place when pressure is applied, and is free of dirt and debris)',
    'Fixed Dual Slot D-Ring (Strap) (Verify the dual slot D-Ring is fi xed in place and there are no visible cracks or wear)',
    'Accessories (Storage Bag Supplied/Provided)',
    'Manuals (Storage, Assembly and Usage Manuals provided)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  ap: [
    'Operating Voltage ( LV; ≤ 1000V)',
    'Feeder pillar body (Adequately sealed, hot dip galvanised with provision of earthing point)',
    'Lifting lugs (Minimum of two closed lifting lugs)',
    'Feeder pillar Body Finish (Paint should not Peel off and no signs of rust)',
    'Feeder pillar bus bars (1600A bus bars, electro tinned hard drawn high conductivity copper) (Ammeter of accuracy at least +/- 2.5%.,installed):(Voltmeter of accuracy at least at least +/-1.5%.)',
    'Coating Auto recloser Mounting brackets (Hot dip galvanised)',
    'Eartrhing Terminals ( Earthing Terminals  provided with bolt)',
    ' One incomer and four or six or eight outgoing fused circuts (each three phase)',
    'Three current transformers ratio 1600/800/5, class 1.0 10VA',
    'Name Plate(Fitted with a Stainless steel rating plate)',
    ' Circuit identification/labelling facility',
    'Dimensions of feeder pillar (See drawing attached)',
    'The top cover of Feeder pillar shall have inclined surface(s) to avoid Accumulation of rain water. It shall have a canopy over the door',
    'MV Bushing Creepage Distance (≥770mm)',
    ' 13A 3-pin switch socket outlet with plug (square pins)',
    'Ventilation louvres with anti-vermin baffles',
    'Phase barries  provided to prevent insertion of fuse links between contacts of different phases. The barrier shall be of material which does not readily support combustion',
    '3 phase 4-wire fuse unit ( Four,Six. Eight No. 600A with moulded shrouded through grip handles for JPU fuse TYPE)',
    'Test certificates (Routine, type tests, National accreditation of supplier) and schematic wiring diagram'
  ],
  ap: [
    'Operating Voltage ( LV; ≤ 1000V)',
    'Feeder pillar body',
    'Lifting lugs',
    'Feeder pillar Body Finish',
    'Feeder pillar bus bars(Ammeter of accuracy at least +/- 2.5%.,installed):(Voltmeter of accuracy at least at least +/-1.5%.)',
    'Coating Auto recloser Mounting brackets',
    'Eartrhing Terminals',
    ' One incomer and four or six or eight outgoing fused circuts (each three phase)',
    'Three current transformers ratio 1600/800/5, class 1.0 10VA',
    'Name Plate(Fitted with a Stainless steel rating plate)',
    ' Circuit identification/labelling facility',
    'Dimensions of feeder pillar',
    'The top cover of Feeder pillar shall have inclined surface(s) to avoid Accumulation of rain water. It shall have a canopy over the door',
    'MV Bushing Creepage Distance',
    ' 13A 3-pin switch socket outlet with plug (square pins)',
    'Ventilation louvres with anti-vermin baffles',
    'Phase barries  provided to prevent insertion of fuse links between contacts of different phases. The barrier shall be of material which does not readily support combustion',
    '3 phase 4-wire fuse unit',
    'Test certificates (Routine, type tests, National accreditation of supplier) and schematic wiring diagram'
  ],
  aq: [
    'Ferrule Size (sq.mm) (35),(70),(95),(100),(150),(185),(240),(300)',
    'Ferrule Material (Aluminium)',
    'Overall Ferrule Length (≥56.0),(≥73.0),(≥78.0),(≥89.0),(≥91.0),(≥104.0),(≥124.0),(≥194.0)',
    'Overall Diameter Of Ferrule (≥10.8),(≥16.0),(≥17.1),(≥19.6),(≥21.5),(≥24.0),(≥28.6),(≥30.0)',
    'Inner Diameter Of Ferrule (≥8.5),(≥11.6),(≥12.9),(≥14.8),(≥15.9),(≥19.0),(≥22.0),(23.5)',
    'Ferrule Thickness (≥1.15),(≥2.2),(≥2.1),(≥2.4),(≥2.5),(≥2.5),(≥3.3),(≥3.25)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  ar: [
    'Material (polyurethane)',
    'Container Size (≥250ml)',
    'Colour (Grey, white)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  as: [
    'Material (Pure Leather)',
    'Colour (Red)',
    'Inside Finish (Soft Inner Lining)',
    'Length',
    "Finish (Shouldn't have any tear or damage)",
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  at: [
    'Guy grip size (7/8 swg):(7/12 swg) ',
    'Guy grip Material (Galvanised Steel)',
    'Number of stands (Strand diameter -4mm (6):(Strand diameter -3mm (5)',
    'Direction of lay(Right hand lay)',
    "The guy grip shouldn't have any damage",
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  au: [
    'Blade Material (High grade Bi-Metal)',
    'Blade Sizes (8, 10 and 12 Blades)',
    'Blade Width (2)',
    'Blade Thickness (0.65mm - 1.0mm)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  av: [
    'Operation of Pallet (Manually Operated)',
    'Load Capacity (≥ 3000kg)',
    'Length of the forks (≥ 1000mm)',
    'Lift height(≥ 200mm)',
    'Turning radius (180)',
    'Width across the forks (≥ 500mm)',
    'Steering wheel (Insulated with rubber)',
    'Design of load wheels (4 of polyurethane)',
    'Finishing of metallic parts (Rust resistant coarting)',
    ' Material of metallic parts ( High grade Steel alloy)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  aw: [
    'Material (HDPE ( high density polyethylene)',
    'Colour (white)',
    'Suspension (8 point plastic for shock absorption)',
    'Sweat band (Synthetic fibers (polyamide or polyester)',
    'Design Distinctive (aerodynamic, Scalloped with Integral rain channel)',
    'Adaptability (Ability to add ear muffs and miners lamp at forehead)',
    'Ventilation (Not less than four vent holes at the highest points to facilitate the cool flow of air and maximize comfort)',
    'Nape strap (Adjustable nape positions to provide right fit comfort and protection to the wearer)',
    'Labels (Name / trademark of manufacturer, Applicable Standards,  Care and cleaning Instructions & Sizes)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  ax: [
    'Pipe Material (Hardened Plastic)',
    'Pipe Diameter (≥160mm)',
    'Thickness of Pipe (≥3.68mm)',
    'Colour (Grey/Black/White)',
    'Finishing (Smooth Finish)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  ay: [
    'Herbicide Type (Non-Selective)',
    'Active Ingredient',
    'Means of uptake (Both Contact and Systemic)',
    'Soil persistance (Minimum of 1 year)',
    'Brand Name',
    'Chemical Name',
    ' Expiry date/ Self life',
    'Packing ( Must have an attached label providing instructions for storage and disposal, use of the product, and precautions for the user and the environment)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  az: [
    'Nominal System Voltage, (33kV)',
    'Highest System Voltage, (36kV)',
    'Colour (red/black)',
    'Material (good quality rubber)',
    'Class (4)',
    'Length, (410/460mm)',
    'b)Max. Thickness, (3.6mm)',
    'Size, (8,9,10,11 mm)',
    'Oil Resistance',
    'Acid Resistance',
    'Flame retardant',
    'High temperature resistance',
    'Symbol for live working',
    'Applicable standard with year of publication',
    'Category',
    'Size',
    'Class',
    'Date of manufacture',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  ba: [
    'Handle Material (Plastic Material)',
    'Blade Material (Hardened Steel)',
    'Design (With insulated cover)',
    'Blade Length (2)',
    'Overall length(8.5)',
    'Finish (Smooth Finish)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  bb: [
    'Insulating Tape Material (Vinyl Plastic)',
    'Tape color (Black, Red & Blue)',
    'Thickness(0.19 mm)',
    'Width (20 mm)',
    'Core Diameter, min (31.5 mm)',
    'Roll Length (10 m)',
    'Voltage Rating (Low Voltage (600V)',
    'Properties After Application/ Use (No Cracking, No breakdown, No unwinding)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  bc: [
    'IPC Model (Customer Service Connection), (main to main connection),(LV bare to LV ABC connection)',
    'Mail Line Cable Size (35, 54.6, 70mm² LV ABC), (35, 54.6 or 70mm² LV ABC),(LV-Bare(50sqmm-150sqmm))',
    'Tap- Line Cable Size (T-off)(10 to 25mm²), (35, 54.6 or 70mm² LV ABC), (35, 54.6 or 70mm² LV ABC)',
    'IPC Insulation Material (Glass Fibre Reinforced Polymer)',
    'Contact Plates Material (Aluminium/Copper/Tinned Copper)',
    'Shear Bolt Material (Steel with Geomet(Cr.) Protection)',
    'IPC Construction (Flexible End Caps attached to IPC Body)',
    'IPC Colour (black)',
    'Metal Parts Design (Corrosion Resistant)',
    'IPC Water Proof?(yes/no)',
    'Markings',
    'Test Certificates and Type Test Reports'
  ],
  bd: [
    'Material (Hot Dip Galvanised Steel)',
    'Landing Bracket Dimensions ((56mmx46mm/56mmx46mm)',
    'Diameter and Number of Holes (2 Hole - D20mm)',
    'Thickness of Landing Bracket (3mm)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  be: [
    'Lug Size(sq.mm) (1.5),(2.4),(4),(70),(95),(100),(120),(150)',
    'Lug Material(Aluminum, Copper or Bi-Metal)',
    'Overall Lug Length (≥47.0(Cu.),(≥73.0(Al.),(≥78.0),(≥60.0(Cu.),≥89.0(Al.Bi),(≥71.0))',
    'Overall Diameter Of Sleeve (≥14.5(Cu.), ≥16.0(Al.),(≥17.1),(≥19.5(Cu.), ≥19.6(Al.),(≥21.5))',
    'Inner Diameter Of Sleeve (≥11.5(Cu.), ≥11.6(Al.),(≥12.9),(≥16.0(Cu.), ≥14.8(Al.),(≥16.5))',
    'Sleeve Thickness (≥1.5(Cu.), ≥2.2(Al.),(≥2.1),(≥1.75(Cu.), ≥2.4(Al.),(≥2.5(Cu))',
    'Stud/Hole Diameter Of Lug(≥13(Cu.), ≥13(Al), (≥12.7),(≥13(Cu.), ≥12.7/24.0(Al.),(≥13))',
    "Lug Finish (Shouldn't be damaged)",
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  bf: [
    'Cable Size (35mm²),(70mm²),(95mm²),(185mm²),(240mm²),(300mm²)',
    'Insulation material (XLPE)',
    'Insulation thickness (Thickness of Insulation (mm) (≥1.1),(≥1.6),(≥1.7),(≥1.8)',
    'Material of Armour (Steel Armour)',
    'Oversheath Thickness (Thickness of Oversheath (mm) (≥1.8), (≥2.1),(≥2.4),(≥2.5)',
    'Armour Diameter (Nominal armour wire diameter (mm) (2),(2.5)',
    'Insulation screen thickness (0.3mm)',
    'Outer sheath material(PVC, ST2 or PE ST7)',
    'Overall Diameter (Approx. Overall Diameter (mm) (≥30.7),(≥36.8),(≥41.4),(≥56.5),(≥63.3),(≥63.4)',
    'Strand Diameter (Norminal Strand Diameter (mm) (≥1.6)',
    'Current carrying capacity(state)',
    'When delivered to the site, cable ends should have cups',
    "The outer sheath shouldn't have any damage",
    "The delivery drum shouldn't be damaged",
    'The cable should have markers showing (Its rating, year of manufacture and size)',
    'Conductor (Aluminium)',
    'Over sheath (Shall be extruded PVC)',
    'Armour (Non magnetic material. Aluminium or aluminium alloy of thickness)',
    'For three phase cables, phase colour of red, yellow and blue',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  bg: [
    'Material (Porcelain)',
    'Creepage Distance',
    'Diameter of Hole (≥5/8/M16)',
    'Overall Diameter of Insulator',
    'Surface Finish (Smooth Glaze)',
    "Insulator shouldn't have any damage",
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  bh: [
    'Rating and Number of Poles (Single Pole (SP) 63A, SP)',
    'Tripping Mechanism (Hydraulic-Magnetic)',
    'Type of mounting (DIN Rail Mounting)',
    'Housing Material (Molded case Plastic or Bakelite pigmented black/grey with white handle)',
    'MCB Termination Construction and Fitting (Screw Or Pressure Type, suitable for applicable Lug size)',
    'MCB Terminal Material(Tinned Copper)',
    'Interphase barriers (Fitted with high dielectric insulating plates)',
    "MCB outer surface finish (The outer surface of the MCCB shouldn't have any damage)",
    'Markings (Property of Umeme Ltd on the MCCB)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  bi: [
    'Rating and Number of Poles (Single Pole (SP)/ Three Pole (TP) (100A SP),(150A SP),(200A SP),(250A TP),(300A TP),(400A TP)',
    'Tripping Mechanism(Hydraulic-Magnetic)',
    'Type of mounting (Pole Mounting)',
    'Housing Material (Molded case Plastic or Bakelite pigmented black/grey with white handle)',
    'MCCB Termination Construction and Fitting (Pressure Type, suitable for 35/M8, 70/M12, 120/M12, 185/M12, 240/M16 Lug size):(Circuit Break should have an extension for easy termination of all cable lug sizes)',
    'MCCB Terminal Material (Tinned Copper)',
    'Interphase barriers (Fitted with high dielectric insulating plates)',
    "MCCB outer surface finish (The outer surface of the MCCB shouldn't have any damage)",
    'MCCBs Should Have MCCB Enclosure Boxes (Danger sign and Umeme Log on the MCCB Enclosure)',
    'MCCB Enclosure Material (Water Proof, hard plastic  pigmented white)',
    'Markings (Property of Umeme Ltd on the MCCB)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  bj: [
    'Material (Polycarbonate)',
    'Material Construction (Fully Transparent)',
    'Type (Anchor type with Dual stage locking mechanism)',
    'Colour (Coloured male part and colourless female part)',
    'Features (Embossed barcode and monogram in circle)',
    'Thickness of seal (Minimum of 1mm)',
    'Accessories (Seal wire should be provided)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  bk: [
    'Voltage Level (33kv 11kv)',
    'Cooling System (Oil Cooled)',
    'Configuration (3 phase-3wire/3 phase-4wire)',
    'Construction (CT/PT Combined Metering Unit)',
    'Bolts and Nuts with washers (Shall be corrosion resistant)',
    'Design (Pressure Relief Valve fitted at top cover of metering unit tank)',
    'Lifting lugs (Minimum of two closed lifting lugs)',
    'Bushings (Should not be cracked)',
    'Metering Unit Body Material (Galvanised Steel)',
    'Metering Unit Body Finish (Powder Coated)',
    'Mounting (Mounting Brackets accessories should be provided for Pole Mounting)',
    'Eartrhing Terminals (Multiple Earthing Terminals should be provided)',
    'Working Conditions (Out Door Use)',
    'Dimensions of Metering Unit tank (As per Technical Drawings)',
    'Name Plate (Fitted with a Stainless steel rating plate)',
    'Bush Terminal markings (Incoming and Outgoing Markings on Bushings)',
    'MV Bushing Material (Porcelain)',
    'MV Bushing Creepage Distance (≥900mm)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  bl: [
    'Insulation material and thickness (XLPE. 8mm/33kV and 3.4mm/11kV)',
    'Insulation screen thickness (0.3mm)',
    'Outer sheath material (PVC, ST2 or PE ST7)',
    'Conductor Diameter (State measured value)',
    'When delivered to the site, cable ends should have cups',
    "The outer sheath shouldn't have any damage",
    "The delivery drum shouldn't be damaged",
    'The cable should have markers showing',
    'Conductor (Copper/ Aluminium)',
    'Over sheath (Shall be extruded PVC)',
    'Armour (Non magnetic material. Aluminium or aluminium alloy of thickness)',
    'For three phase cables, phase colour of red, yellow and blue',
    'Insulation Resistance Test (Red - Earth):(Yellow - Earth):(Blue - Earth):(Red - Blue):(Red - Yellow):(Yellow - Blue)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  bm: [
    'Crossarm dimensions (Length x thickness) (2591X9.5mm)',
    'Material (Hot Dip Galvanised Steel)',
    'Diameter of holes on cross arm()23.8mm',
    'Phase to Phase Clearance (900mm/600mm)',
    "The cross arm body shouldn't have any damage",
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  bn: [
    'Nail Size',
    'Material (Galvanised Steel)',
    'Length of Nail(mm)',
    'Diameter of Nail Shaft (mm)',
    'Design of Nail(Flat Head Nail)',
    'Finish (Corrosion Resistant Finish)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  bo: [
    'Block Material (Brass)',
    'Casing Insulation (Thermosetting Plastic housing)',
    'Housing Material (DIN Rail Mounting)',
    'Housing Material Colour (Grey)',
    'Dimension (56mm long x 6mm thick x 10mm high)',
    'Hole Number and Dimensions (4 holes each of 1.5 to 16mm²)',
    'Mounting (Wood Boards with Wood screws)',
    'Markings (Property of Umeme Ltd on the MCCB)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  bp: [
    'Material (Chrome Vanadium Steel)',
    'Length (≥156mm)',
    'Type of Construction (Open and Ring Ended)',
    'Size (10mm)',
    'Handle Insulation Material (Ragged, Permanently fixed and made of Vinyl Material)',
    'Finish (Chrome Finish)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  bq: [
    'Type Of Spanner (Should be Open,Rinf or Combined)',
    'Material (Chrome Vanadium steel Alloy)',
    'Material finish (Chrome Plated)',
    'Sizes in a set (6x7 to 30x32)',
    'When delivered should be in a set (Set of 12)',
    'Storage (Pouch bag/Handy storage wallet)',
    'Labelling of the spanners in the set (Size and material to be indicated)',
    "Condition of the spanner (Shouldn't be bent or damaged)",
    'Length of each spanner (Should be as labelled)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  br: [
    'Core Design (Core and Cladding surrounding core made of fused Silica)',
    'Primary Coating (Buffer with a suitable UV cured materials of 250 ±15µm)',
    'Secondary Coating (Tight UV Acrylate coating and that is easily removable by mechanical means)',
    'Identification of individual fibres (Colour to allow for unique identification of individual fibres)',
    'Metal free',
    'Jointing (Fibres shall have no joints)',
    'Sheathed with  material compatible with cable hauling through ducts and  resistant to insect and termite attack',
    'Sheath resilient to heat and UV radiation',
    'ADSS 48 core single mode',
    ' Span length of up to 200 meters',
    '2 red ripcords each for outer and inner cable jackets',
    'Designed with dry water blocking materials only',
    ' 4 loose tubes each 12 fibers dry, no gel',
    'Designed for use on distribution and high voltage transmission lines',
    'No messenger wire - fully self-supporting',
    'Capable of being installed in close proximity to live conductors',
    'Water - blocked using dry core technology',
    'markings'
  ],
  bs: [
    'Outrigger Material (Hot Deep Galvanised Steel)',
    'Outrigger Strut Diameter(mm)',
    'Outrigger Strut Dimensions (Short=760mm, Long≥1150mm)',
    'Base Holes (4)',
    'Surface finish (Smooth and free from rust)',
    "Physical Damage (Shouldn't be bent)",
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  bt: [
    'Nose Material (Hardened Steel)',
    'Size/Gath of Nose (mm)',
    'Openning and Locking (Must be with Key)',
    'Package (Supplies with extra Keys) ',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  bu: [
    'Sign Material',
    'Sheet Finish',
    'Paint Composition (High Gloss Baked Enamel Finish)',
    'Letterings (White with a Red Background)',
    'Wording Printing (Screen Printed)',
    'Dimensions of Danger Sign Plate(mm)',
    'Number and Diameter of holes for Nailing',
    'Corner Finishing (Rounded Off smoothly and Blunt)',
    'Wording Languages (English)',
    'Markings',
    'Test Certificates and Type Test Reports'
  ],
  bv: [
    'PG Clamp Material (Al. - Al. or Al.-Cu.)',
    'Number of bolts (2,3 or 4)',
    'PG Bolts (Grade 316 Stainless steel)',
    'Washer dimensions (Diameter and thickness 17x2.5mm)',
    'PG Bolt Dimensions (M8 x 45mm)',
    'Conductor range: Al-Al (25 to 200mm²)',
    'Conductor range: Bimetallic (Main conductor -25 to 200mm²):(Tap conductor -16 to 185mm²)',
    'Filler content (oxide inhibiting grease or compound)',
    'Conductor range: Al-Al (25 to 200mm²)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  bw: [
    'Pig Tail Size (M16X300mm)',
    'Material (Hot Dip Galvanised Steel)',
    'Pig Tail bolt and Nut Manufacture (Drop Forged Manufacture)',
    'Length of Pig tail bolt (430mm)',
    'Length of Threaded part (300mm)',
    'Diameter of the unthreaded part (16mm)',
    'Nuts and Washers',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  bx: [
    'Material (Hot Dip Galvanised Steel)',
    'Pig Tail Coach Screw Manufacture (Drop Forged Manufacture)',
    'Length of Pig Tail Coach Screw (100mm)',
    'Length of Threaded part (76mm)',
    'Outer Diameter of Pig Tail Bend (40mm)',
    'Diameter of Pig Tail Body (7.8mm)',
    'Inner Diameter of Pig Tail Bend (25.8mm)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  by: [
    'Material (Porcelain)',
    'Colour (brown)',
    'Creepage Distance (≥825mm)',
    'Nominal Diameter (≥210mm)',
    'Nominal height (≥272mm)',
    'Surface Finish (Smooth Glaze)',
    "Insulator shouldn't have any damage",
    'Markings (Type of insulator, Reference Standard,R90, 33kV)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  bz: [
    'Material (High grade Steel/ Aluminium Casting)',
    'Diameter of Pole Cap(310mm)',
    'Thickness of Sheet (1mm)',
    'Number of Holes (2)',
    'Diameter of Holes (330mm)',
    'Surface Finish of Pole Cap (Smooth Galvanised Surface with blunt ends)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  ca: [
    'Pole saver size (20,25,30cm diameter)',
    'Pole saver Material (Tough UV stabilized polyethylene)',
    'Pole saver has BUTUMINOUS layer/sealant',
    'No cuts or holes observed',
    "Markings ( Manufacturer's name): ( Size of pole saver): ( Year of manufacture): ( ISO Certificattion):(Pole saver shrinks tightly around pole under heat using a blow torch):(Pole saver dimensions - Length= 700mm, Width= 300mm or 370mm,Thickness≥2mm)",
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  cb: [
    'Make-Off Size (7/12 - 7/8)',
    'Material (Galvanised Steel)',
    'Diameter of Strands(mm) (2.6) (4.02)',
    'Overall Diameter of Strands (8.13), (11.4)',
    'Length of Make Off- Wrap (2290)',
    'Approximate Diameter of Make Off Wrap (200) (270)',
    'Approximate Length of Make Off Wrap (430) (640)',
    'Number of Strands (7)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  cc: [
    'System Voltage (11kv & 33Kv)',
    'Material of core rod (Glass-Fiber Reinforced Epoxy Resin Rod)',
    'Creepage distance (320 & 900mm)',
    'Material of Housing & weather sheds (Silicone Electrometric Compound (Polymer)',
    "Mounting Accessories and Brackets (Supplied with Two 3/4x12'' Bolts and Nuts and any other accessories)",
    'Design Construction (Extruded or Directly Molded on the Core)',
    'Insulator Design (With a two bolt gain base and a clamp on top)',
    'Colour of Insulator (Grey/Light blue)',
    'Thickness of housing (3mm minimum)',
    'Ferrous parts material (Hot Dip Galvanized)',
    'Markings (legibly and indelibly marked)',
    'Number and Diameter of Gain Base Holes (2 holes of  20mm Diameter)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  cd: [
    'Pre-Formed Dead End Size (sq.mm)',
    'Pre-Formed Dead End Material (Aluminium clad steel)',
    'Number of strands of Dead end',
    'Direction of lay (right hand lay)',
    'Dimension of Dead end (Refer to Technical Drawing)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  ce: [
    'Cross Arm Material (Mild Steel)',
    'Thickness of cross arm material (≥3mm)',
    'Jointing (Welded)',
    'Surface Finish (Hot Dip Galvanised Steel)',
    'Dimensions (L ≥ 1040, W = 420, W2 c/c = 360)',
    'Bolt Sizes (M6 Bolts and Nuts-16 Number)',
    'Bolts, Nuts and Washer Coating (Hot Dip Galvanised Steel)',
    "Cross Arm shouldn't have any damage",
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  cf: [
    'Colour (blue)',
    'Opening Closure (Over lapping front button down with press button)',
    'Design (Worn over every day clothes)',
    'Inner materials (Soft water proof silk linning fot extra comforrt)',
    'Fabric (100% Nylon,Plain weave)',
    'Application (Water proof)',
    'Finishing (Comfort and well trimed)',
    'Pockets (Two front pockets with overlapping covers)',
    'Reflection (Visible reflection band)',
    'Logo and Labelling (Screen printed umeme Logo)',
    'Head protection (Non-detachable hood)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  cg: [
    'Board dimensions (Length x Width) (As per Technical Drawing)',
    'Material of ready board (Injection Moulded Plastic)',
    'Colour of board (grey)',
    'Type of mounting (Wall mounting with four mounting screws)',
    'No. and type of light/lamp (1 Bulkhead CFL/LED Light)',
    'No. and type of sockets (3, 13A Single square pin socket outlets)',
    'Rating of MCB for light and socket (3A and 20A)',
    'Rating of lamp (20W)',
    'Dimensions of lamp ((240x120x120) mm)',
    'No. of access points for conduit or twin and earth cable (6)',
    "The ready board shouldn't have any damage",
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  ch: [
    'Shoe Make/Type (LongNeck or Short Neck)',
    'Upper Shoe Material (High Grade  Full grain Leather)',
    'Collar  Construction ( Padded for comfort)',
    'Inner Lining (Needle-fibred vamp lining for perspiration absorbency)',
    'Midsole Construction ( Shank Midsole Steel Reinforcement for Arch Support)',
    'Toe Cap Construction (Wide fitting steel Toe Cap)',
    'Sole Design (Oil and acid resistant Double density PU sole)',
    'Colour (black)',
    'Labellings (Size and Brand)',
    'Test Certificates and Type Test Reports'
  ],
  ci: [
    'Type of screw driver (Should be Flat/Star)',
    'Tip  Material (Hardened Steel)',
    'Nature of the tip (Magnetic)',
    'Handle construction (Comfortable and grippy)',
    "Condition of the screw drivers (Should't be bent or damaged)",
    'When delivered should be in a set (Set of 8 or 12)',
    'Storage (Pouch bag/Handy storage wallet)',
    'Material of the shaft (Heat treated chrome vanadium steel)',
    'Name of manufacturer,Size indicated (Marked on the screw driver)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  cj: [
    'Material (Stainless Steel)',
    'Head Type(Combination Drive Pan Head)',
    'Length  of Screw (28mm)',
    'Length of Threaded part (Fully Threaded)',
    'Diameter of Screw Shaft (4.15mm)',
    'Diameter of Screw Head (8mm)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  ck: [
    'Material of Meter body (Heavy Duty PVC)',
    'Dimensions of the Meter (170mm(H) x60mm(w) X100mm (D)',
    'Terminal Tamper Cover (Installed and Operational)',
    'Terminal Material (Brass/nickel plated brass)',
    'Spring loaded inspection window (Capable of automatic reclosure once opened)',
    'Meter Body Colour (dark grey /light beige)',
    'metallic trainagular head screw (provided)',
    'Meter Box Material (Heavy Duty PVC)',
    'Meter Box Material Design (Inbuilt DIN Rail Provision)',
    'Meter Box Material Dimensions (300mm(H)x 140mm(w)x 130mm(D))',
    'Meter Box Material Thickness(3mm)',
    'Meter Box Material Colour (Dark Grey/ light beige)',
    'Smart Card (Latest Umeme brand and Contact Number)',
    'Accessories (Bandit strap ties and buckle straps)',
    'UIU body (No damages)',
    'UIU Cable (Cable should be non detachable)',
    'Meter Wiring (Should be Pre-Wired)',
    "Markings ( purchaser's name, name of the manufacturer, country of origin,Box serialized number, year of manufacturer and sign of danger)",
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  cl: [
    'Material (High grade carbon steel )',
    'Ferrous parts material (Hot Dip Galvanised Steel)',
    'Design of Thimble (Supplied with a stainless steel split pin)',
    'Split pin lock',
    'Diameter of the hole (36.7mm)',
    'Finish (Smooth, Continuous and Uniform Hot Dip Galvanizing)',
    "Markings (Manufacturer's identification and Minimum failing load in kN)",
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  cm: [
    'Material PVC (Polyvinyl chloride)',
    'Colour (black)',
    'Clip Brand (tower)',
    'Clip Diameter (16mm)',
    'Clip Nail (Pre-Installed Steel Galvanised fastener Nail)',
    'Packaging (Boxes/Polythene Bags)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  cn: [
    'Material (High Grade Steel)',
    'Ferrous parts material (Hot Dip Galvanised Steel)',
    'Length of Spindle (282mm)',
    'Diameter of Spindle Stud (22mm)',
    'Additional Components (Two nuts, a spring and two circular flat washers)',
    'Finish (Smooth and Uniform thickness of Zinc coating without any sharp edges)',
    "Markings (Manufacturer's identification and Minimum failing load in kN)",
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  co: [
    'Spindle Material (High grade steel)',
    'Spindle nuts (Spindle supplied with 2 nuts( one bigger than the other)',
    'Spindle washers (Spindle supplied with one spring washer and 2 circular flat washers)',
    'Application on pin insulators (Spindle suitable for use on pin insulators of R90, R70,R50)',
    'Method of galvanizing ferrous parts (Hot dip galvanised)',
    'Finish (Smooth and uniform thickness without any sharp edges and signs of rust)',
    ' Dimensions of spindle (800Ib spindle: Length of unthreaded head to base=  240mm, Length of threaded part from base=52.27mm                            Pilot spindle: Length of unthreaded head to base= 400  Length of threaded part from base=150)',
    'Test certificates (Routine, type tests)'
  ],
  cp: [
    'Joint(Splice) Type (Insulated-Compression Type)',
    'Joint(Splice) Material (Aluminum)',
    'Overall Splice Diameter (14.6mm)',
    'Inner Diameter Of Splice (11.2mm)',
    'Splice Thickness (1.7mm)',
    'Sizes and Color Codes(Red for 35mm²,  Black for 54,6mm²,White for 70mm²)',
    'Additional Features of Sleeve (A conductor stop positioned at the centre of the sleeve barrel)',
    'Compression fittings (Prefilled with jointing compound)',
    "Sleeve/Splice Finish (Shouldn't be damaged)",
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  cq: [
    'Bracket dimensions (Length x thickness) (As per Technical Drawing)',
    'Material (Hot Dip Galvanised Steel)',
    'Diameter of holes on cross arm (M20)',
    "The Bracket shouldn't have any damage",
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  cr: [
    'System Voltage (medium voltage),(low voltage)',
    'Insulator Type (Strain Type)',
    'Insulator Material (Porcelain)',
    'Insulator Material Finish (Smoothly glazed and of uniform brown colour when finish)',
    'Dimensions (LXW), mm (170 X 80),(90 X 60)',
    'Creepage distance, mm (77),(42)',
    'Groove diameter(Dia B as per the drawing) (60),(42)',
    'Overall diameter( Dia A as per the drawing)(80),(60)',
    'Diameter of the holes (26),(17)',
    'Markings (Name of the manufacturer, standards)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  cs: [
    'Tubular Stay Rods Size (6ft x 7/12):(8ft x 7/8)',
    'Turnbuckle Double eye bolt Size (15 X 7/12) :(15 X 7/8)',
    'Size of Stay Wire (7/12 swg):(7/8 swg)',
    'Stay Rod Length (≥1830mm):(≥2430mm)',
    'Thimble',
    'Eye Nut Diameter (25mm):(30mm)',
    'Length of Turn Buckle (≥400mm)',
    'Length of Threaded part on Stay Rod (≥240mm):(≥250mm)',
    'Diameter of Stay Rod (≥15mm:≥22.3mm)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  ct: [
    'System Voltage (11kv), (33kv)',
    'Material of core rod (Glass-Fiber Reinforced Epoxy Resin Rod)',
    'Creepage distance (240m), (720m)',
    'Insulator Type (Tongue & Clevis type)',
    'Material of Housing & weather sheds (Silicone Electrometric Compound (Polymer)',
    'Design Construction (Have a core, housing, weather shed of insulating material and steel/aluminum alloy hardware components)',
    'End Fittings Design/Material (Spheroidal graphite cast Iron, Malleable cast iron, Forged steel or Aluminum alloy)',
    'Colour of Insulator (Grey/Light blue)',
    'Thickness of housing (3mm minimum)',
    'Ferrous parts material (Hot Dip Galvanized)',
    'Markings (legibly and indelibly marked)',
    'Surface Finish (Metal parts shall be perfectly smooth without projecting points or irregularities)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  cu: [
    'Crossarm dimensions (Length x Width x Thickness)',
    'Material (Hot Dip Galvanised Steel)',
    'Diameter and Number of holes on Strut (mm) (2XM20)',
    "The cross arm body shouldn't have any damage",
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  cv: [
    'System Voltage (11kv / 33kv)',
    'Creepage distance greater than 31mm per kV (>1116mm),(>372mm)',
    "Insulation Material (Shouldn't have any Damage)",
    'Class of surge arrestor (Distribution class)',
    'Nominal discharge current (10kA)',
    'Type (Gapless metal oxide)',
    'Housing material (Polymeric/Porcelein insulator)',
    'Mounting Brackets',
    'Cords/lugs/bolts & nuts',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  cw: [
    'Material (Mineral Turpentine)',
    'Container Material (Tight Steel Can)',
    'Container Size (30 Litters)',
    'Colour (white)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  cx: [
    'Material (PVC (Polyvinyl chloride)',
    'Colour (white)',
    'Clip Brand (tower)',
    'Clip Diameter (4mm)',
    'Clip Nail (Pre-Installed Steel Galvanised fastener Nail)',
    'Packaging (Boxes/Polythene Bags)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  cy: [
    'Oil appearance (Clear, transparent and free from suspended matter or sediments and moisture)',
    'Viscosity of oil (LOW; Oil flow is NOT significantly impended)',
    'Volatility of oil (LOW; Oil should NOT form steam/ vapour when is in open)',
    "Manufacturer's name",
    ' Expiry date',
    'Packing (Packed in steel drums coated with rust preventive material and properly sealed any ingress of moisture)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  cz: [
    'Test certificates (Routine, type tests, National accreditation of supplier)',
    'Rated continuous current, A (1, 2, 3, 5, 6, 8, 10, 12, 15, 20, 25, 30, 40 or 50)',
    'Min. current breaking capacity, kA (8)',
    'Min tensile withstand strength (4.5 kg)',
    'Fusing element material (tin)',
    'Diameter of removable washer (19 mm)',
    'Diameter of button head cap(13mm)',
    'Overall length of fuse link (787mm)',
    'Fusing element paper cover',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  da: [
    'Material (Plastic)',
    'Colour (Cream/White/Black)',
    'Drill Diameter (7mm)',
    'Approximate Pieces Per pack (300)',
    'Suitable Screw Size (4-7mm)',
    'Applicable Material (Concrete/Brick Walls)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  db: [
    'Bolt Diameter (M16(5/8) (M20(3/4))',
    'Type of Washer (Round flat ,Square Curved)',
    'Material (Hot dip galvanized steel)',
    'Washer Dimensions (Round-30mm Curved-65 x 65mm)',
    'Washer Thickness (4mm)',
    'Material used in galvanizing (Zinc)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  dc: [
    'Product Name should be Megger',
    'Type',
    'Test Voltage up to 50V',
    'Measuring Range -Up to 20 Kilo Ohoms',
    'Imput Power-Chargable internal battery',
    'Batery Life-More than 3000 tests',
    'Battery Type - 8XAA',
    'Test Leads to be Four of different colors',
    'Earth Pikes to be Four in number',
    'Box should be of Hard material',
    'Test certificates'
  ],
  dd: [
    'Material (Chrome Vanadium Steel)',
    'Size of the Adjustable (300x36mm)',
    'Nature of the Jaw Face (Should be polished)',
    'Handle Construction (Insulated)',
    'Jaw Adjustment (Easily Adjustable)',
    'Handle Insulation Material (Ragged Permantly fixed and made of Vinyl Material)',
    "Physical Damage (Shouldn't be damaged or bent)",
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  de: [
    'Strap Material (Stainless Steel)',
    'Strap Thickness (1.0mm)',
    'Strap Width (Min. 6.35mm)',
    'Strap Diameter (Min. 150mm)',
    'Surface finish (Bright Polished Finish)',
    "Physical Damage (Shouldn't be bent)",
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  df: [
    'Material (High Quality Steel)',
    'Operating Handle (Complete, Robust and Suitable for Manual operation)',
    'Spiral Flute (Long, Deep and Eyed round Sunk)',
    "Cutting Diameter (1''(25.4mm) 3/4''(19.54mm)",
    'Length (400mm to 450mm and 200mm)',
    'Bit Treatment (Heat Treated Bits)',
    'Type of Bit (Should be Resharpenable)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  dg: [
    'Material (Steel)',
    'Construction (Drop forged tool with built in cutter)',
    'Band widths ( 3/16 - 3/4)',
    'Finish Material (Blue epoxy powder coated)',
    "Physical Damage (Shouldn't be damaged)",
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  dh: [
    'Strap Material (Stainless Steel)',
    'Strap Thickness (1.0mm)',
    'Locking Mechanism (Ear-lokt buckles)',
    'Strap Dimensions (L=34mm, W=25mm)',
    'Strap Hole Dimension (17mm)',
    'Surface finish (Bright Polished Finish)',
    "Physical Damage (Shouldn't be bent)",
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  di: [
    'Material (Flexible Aluminium Plate)',
    'Dimensions (140mm long, 90mm wide and 1mm thickness)',
    'Mounting Hole size and Number (2 holes of 5mm diameter)',
    'Lettering (Engaved or Screen Printed)',
    'Surface Finish (Smooth and free from damage)',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  dj: [
    'Type of Treatment(Creosote or CCA)',
    'Is the pole free of rot (Free)',
    'Minimum Pole Top Diameter (150mm)',
    'Is the pole free of cracks (Acceptable cracks)',
    'Is the pole circular (not elliptical)(Circular)',
    "Nail, spikes shouldn't be on the pole (Spike free)",
    'Top pole formation (Flat)',
    'No mechanical damage (No Damage)',
    "Depressions having bark shouldn't be deeper than 50mm (Depression/Bark free)",
    "The butt shouldn't be defective (Flat butt)",
    'Nail/split plate (Installed)',
    'Pole dimensions should be according to specs. (12m, 14m, 16m):(1m, 12m, 14m, 16m)',
    'Pole Markings (Length, treatment, Year, Insignia, Manufacturer, Species)',
    'Penetration depth (test)',
    'Min. Preservation retention (160Kg/m³/14Kg/m³CCA)',
    'Strength test report',
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  dk: [
    'Strap Material (Galvanized Steel)',
    'Strap Thickness (8.0mm)',
    'Strap Dimensions (L=125mm, W=48mm)',
    'Strap Hole Dimension (20mm)',
    'Surface finish (Bright Polished Finish)',
    "Physical Damage (Shouldn't be bent)",
    'Test certificates (Routine, type tests, National accreditation of supplier)'
  ],
  dl: [
    'Electrical Controls (ECS):(Fabricated):(Can accommodate up to 6 meters only)',
    'Aluminiam - New (All  8 Meters fit well)',
    'New type (Misaligned slots  and holes)',
    'Fabricated (Misaligned slots  and holes.Takes only 6 meters)',
    'Fabricated / New  X-arms (Both new and Fabricated X-arms were OK Takes  8 meters)'
  ]
};

export default paramData;
