-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jan 31, 2023 at 06:41 PM
-- Server version: 10.4.27-MariaDB
-- PHP Version: 8.1.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `warehouse`
--

-- --------------------------------------------------------

--
-- Table structure for table `checklists`
--

CREATE TABLE `checklists` (
  `id` int(11) NOT NULL,
  `material_name` text NOT NULL,
  `supplier_name` varchar(150) NOT NULL,
  `method_of_inspection` varchar(50) NOT NULL,
  `contact_number` int(11) NOT NULL,
  `total_inspected` int(11) NOT NULL,
  `total_pass` int(11) NOT NULL,
  `total_failure` int(11) NOT NULL,
  `delivery_note` varchar(150) NOT NULL,
  `invoice_note` varchar(150) NOT NULL,
  `delivery_date` datetime NOT NULL,
  `inspection_date` datetime NOT NULL,
  `filename` varchar(100) NOT NULL,
  `remark` text DEFAULT NULL,
  `isApproved` tinyint(1) DEFAULT 0,
  `isRejected` tinyint(1) DEFAULT 0,
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `checklists`
--

INSERT INTO `checklists` (`id`, `material_name`, `supplier_name`, `method_of_inspection`, `contact_number`, `total_inspected`, `total_pass`, `total_failure`, `delivery_note`, `invoice_note`, `delivery_date`, `inspection_date`, `filename`, `remark`, `isApproved`, `isRejected`, `createdAt`, `updatedAt`) VALUES
(4, 'Screws', 'ABC Supplier', 'Visual Inspection', 1234, 100, 95, 5, 'DN1234', 'IN1234', '2020-09-30 00:00:00', '2020-09-29 00:00:00', 'screws.pdf', 'No remarks.', 0, 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00'),
(5, 'Nuts', 'XYZ Supplier', 'Visual Inspection', 5678, 100, 98, 2, 'DN5678', 'IN5678', '2020-10-01 00:00:00', '2020-09-30 00:00:00', 'nuts.pdf', 'No remarks.', 0, 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00'),
(6, 'Washers', 'QRS Supplier', 'Visual Inspection', 9012, 100, 99, 1, 'DN9012', 'IN9012', '2020-10-02 00:00:00', '2020-10-01 00:00:00', 'washers.pdf', 'No remarks.', 0, 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00'),
(7, 'Bolts', 'JKL Supplier', 'Visual Inspection', 3456, 100, 97, 3, 'DN3456', 'IN3456', '2020-10-03 00:00:00', '2020-10-02 00:00:00', 'bolts.pdf', 'No remarks.', 0, 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00'),
(8, 'Studs', 'MNO Supplier', 'Visual Inspection', 7890, 100, 94, 6, 'DN7890', 'IN7890', '2020-10-04 00:00:00', '2020-10-03 00:00:00', 'studs.pdf', 'No remarks.', 0, 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00'),
(9, 'Nails', 'ABC Supplier', 'Visual Inspection', 1234, 100, 92, 8, 'DN1234', 'IN1234', '2020-10-05 00:00:00', '2020-10-04 00:00:00', 'nails.pdf', 'No remarks.', 0, 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00'),
(10, 'Brackets', 'XYZ Supplier', 'Visual Inspection', 5678, 100, 93, 7, 'DN5678', 'IN5678', '2020-10-06 00:00:00', '2020-10-05 00:00:00', 'brackets.pdf', 'No remarks.', 0, 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00'),
(11, 'Rivets', 'QRS Supplier', 'Visual Inspection', 9012, 100, 90, 10, 'DN9012', 'IN9012', '2020-10-07 00:00:00', '2020-10-06 00:00:00', 'rivets.pdf', 'No remarks.', 0, 0, '0000-00-00 00:00:00', '0000-00-00 00:00:00'),
(12, 'Rings', 'ABC Supplier', 'Visual Inspection', 1234, 100, 95, 5, 'DN1234', 'IN1234', '2020-09-30 00:00:00', '2020-09-29 00:00:00', 'rings.pdf', 'No remarks.', 0, 0, '2023-01-22 21:10:11', '2023-01-22 21:10:11'),
(13, 'Screws', 'XYZ Supplier', 'Visual Inspection', 5678, 100, 98, 2, 'DN5678', 'IN5678', '2020-10-01 00:00:00', '2020-09-30 00:00:00', 'screws.pdf', 'No remarks.', 0, 0, '2023-01-22 21:10:11', '2023-01-22 21:10:11'),
(14, 'Nuts', 'QRS Supplier', 'Visual Inspection', 9012, 100, 99, 1, 'DN9012', 'IN9012', '2020-10-02 00:00:00', '2020-10-01 00:00:00', 'nuts.pdf', 'No remarks.', 0, 0, '2023-01-22 21:10:11', '2023-01-22 21:10:11'),
(15, 'Bolts', 'JKL Supplier', 'Visual Inspection', 3456, 100, 97, 3, 'DN3456', 'IN3456', '2020-10-03 00:00:00', '2020-10-02 00:00:00', 'bolts.pdf', 'No remarks.', 0, 0, '2023-01-22 21:10:11', '2023-01-22 21:10:11'),
(16, 'Studs', 'MNO Supplier', 'Visual Inspection', 7890, 100, 94, 6, 'DN7890', 'IN7890', '2020-10-04 00:00:00', '2020-10-03 00:00:00', 'studs.pdf', 'No remarks.', 0, 0, '2023-01-22 21:10:11', '2023-01-22 21:10:11'),
(17, 'Nails', 'ABC Supplier', 'Visual Inspection', 1234, 100, 92, 8, 'DN1234', 'IN1234', '2020-10-05 00:00:00', '2020-10-04 00:00:00', 'nails.pdf', 'No remarks.', 0, 0, '2023-01-22 21:10:11', '2023-01-22 21:10:11');

-- --------------------------------------------------------

--
-- Table structure for table `checklisttest`
--

CREATE TABLE `checklisttest` (
  `id` int(11) NOT NULL,
  `material_name` text DEFAULT NULL,
  `supplier_name` varchar(150) DEFAULT NULL,
  `method_of_inspection` varchar(50) DEFAULT NULL,
  `contact_number` int(11) DEFAULT NULL,
  `total_inspected` int(11) DEFAULT NULL,
  `total_pass` int(11) DEFAULT NULL,
  `total_failure` int(11) DEFAULT NULL,
  `delivery_note` varchar(150) DEFAULT NULL,
  `invoice_note` varchar(150) DEFAULT NULL,
  `delivery_date` date DEFAULT NULL,
  `inspection_date` date DEFAULT NULL,
  `filename` varchar(100) DEFAULT NULL,
  `remark` longtext DEFAULT NULL,
  `status` int(11) DEFAULT 0,
  `approved_by` varchar(80) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `checklisttest`
--

INSERT INTO `checklisttest` (`id`, `material_name`, `supplier_name`, `method_of_inspection`, `contact_number`, `total_inspected`, `total_pass`, `total_failure`, `delivery_note`, `invoice_note`, `delivery_date`, `inspection_date`, `filename`, `remark`, `status`, `approved_by`) VALUES
(105, 'fabricated x-arms', 'Equity Suppliers', 'Testing', 781556789, 230, 225, 5, 'delivered at metro', '23456', '2023-01-25', '2023-01-25', NULL, '<div>\n<table>\n<thead>\n<tr>\n<th>Umeme Requirements</th>\n<th>Comment/Remark</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>Electrical Controls (ECS):(Fabricated):(Can accommodate up to 6 meters only)</td>\n<td>pass</td>\n</tr>\n<tr>\n<td>Aluminiam - New (All 8 Meters fit well)</td>\n<td>fail</td>\n</tr>\n<tr>\n<td>New type (Misaligned slots and holes)</td>\n<td>pass</td>\n</tr>\n<tr>\n<td>Fabricated (Misaligned slots and holes.Takes only 6 meters)</td>\n<td>pass</td>\n</tr>\n<tr>\n<td>Fabricated / New X-arms (Both new and Fabricated X-arms were OK Takes 8 meters)</td>\n<td>fail</td>\n</tr>\n</tbody>\n</table>\n<h2>Write a brief comment on Material(s):</h2>\n</div>', -1, '- -> Kwesiga Kato -> Kwesiga Kato -> Kwesiga Kato -> Kwesiga Kato -> Kwesiga Kat'),
(106, 'hexing meter box', 'Apex Suppliers', 'Testing', 23, 234, 234, 12, 'delivered', 'nn5768', '2023-01-27', '2023-01-27', NULL, '<div>\n<table>\n<thead>\n<tr>\n<th>Umeme Requirements</th>\n<th>Comment/Remark</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>External enclosure status</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Antenna cover</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Box labels</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Hinges</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Locking mechanism</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Vents and mesh</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Doors</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Door sensors</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Meter(confirm Modem)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Circuit Breaker</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Cable Jumpers</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Termination screws</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Termination Safety covers</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Termination separators</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Earth loops</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Earthing point</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Knock - out plates</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>AC - DC converter</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>CIU</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Cross arm (2pcs)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Brackets (2pcs)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>L - mounting plate (4 pcs)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>3/4 by 2 bolts (12pcs)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>3/4 by 12 bolts (4pcs)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Flat round washers (32pcs)</td>\n<td>&nbsp;</td>\n</tr>\n</tbody>\n</table>\n<h6>Write a brief comment on Material(s):</h6>\n</div>', -1, ' -> Kwesiga Kato'),
(107, 'transformer oil', 'James', 'Measurement', 2345, 100, 98, 2, 'delivered', '55555', '2023-01-17', '2023-01-18', NULL, '<div>\n<table style=\"width: 69.5538%; height: 176.4px;\">\n<thead>\n<tr style=\"height: 19.6px;\">\n<th style=\"width: 82.587%; height: 19.6px;\">Umeme Requirements</th>\n<th style=\"width: 14.1303%; height: 19.6px;\">Comment/Remark</th>\n</tr>\n</thead>\n<tbody>\n<tr style=\"height: 19.6px;\">\n<td style=\"width: 82.587%; height: 19.6px;\">Oil appearance (Clear, transparent and free from suspended matter or sediments and moisture)</td>\n<td style=\"width: 14.1303%; height: 19.6px;\">pass</td>\n</tr>\n<tr style=\"height: 19.6px;\">\n<td style=\"width: 82.587%; height: 19.6px;\">Viscosity of oil (LOW; Oil flow is NOT significantly impended)</td>\n<td style=\"width: 14.1303%; height: 19.6px;\">pass</td>\n</tr>\n<tr style=\"height: 19.6px;\">\n<td style=\"width: 82.587%; height: 19.6px;\">Volatility of oil (LOW; Oil should NOT form steam/ vapour when is in open)</td>\n<td style=\"width: 14.1303%; height: 19.6px;\">failed</td>\n</tr>\n<tr style=\"height: 19.6px;\">\n<td style=\"width: 82.587%; height: 19.6px;\">Manufacturer\'s name</td>\n<td style=\"width: 14.1303%; height: 19.6px;\">&nbsp;</td>\n</tr>\n<tr style=\"height: 19.6px;\">\n<td style=\"width: 82.587%; height: 19.6px;\">Expiry date</td>\n<td style=\"width: 14.1303%; height: 19.6px;\">pass</td>\n</tr>\n<tr style=\"height: 39.2px;\">\n<td style=\"width: 82.587%; height: 39.2px;\">Packing (Packed in steel drums coated with rust preventive material and properly sealed any ingress of moisture)</td>\n<td style=\"width: 14.1303%; height: 39.2px;\">n/a</td>\n</tr>\n<tr style=\"height: 19.6px;\">\n<td style=\"width: 82.587%; height: 19.6px;\">Test certificates (Routine, type tests, National accreditation of supplier)</td>\n<td style=\"width: 14.1303%; height: 19.6px;\">failed</td>\n</tr>\n</tbody>\n</table>\n<h6>Write a brief comment on Material(s):</h6>\n</div>', -1, ' -> Kwesiga Kato -> Kwesiga Kato -> Kwesiga Kato -> Kwesiga Kato -> Kwesiga Kato'),
(108, 'ABC end cap', 'dd', 'Visual', 3, 3, 3, 333, '33', '333', '2023-01-28', '2023-01-28', NULL, '<div>\n<table>\n<thead>\n<tr>\n<th>Umeme Requirements</th>\n<th>Comment/Remark</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>End cap Size (state)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>End cap Material (UV stabilized insulation rubber)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Design or Construction (Suitably designed for sealing the open ends of insulated conductors against water ingress)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Installation (Can be held in installed position by elastic forces)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Finish (Smooth and uniform thickness without any sharp edges)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Test certificates (Routine, type tests) provide</td>\n<td>&nbsp;</td>\n</tr>\n</tbody>\n</table>\n<h6>Write a brief comment on Material(s):</h6>\n</div>', -1, ' -> Kwesiga Kato'),
(109, 'ABC end cap', 'dd', 'Visual', 3, 3, 3, 333, '33', '333', '2023-01-28', '2023-01-28', NULL, '<div>\n<table>\n<thead>\n<tr>\n<th>Umeme Requirements</th>\n<th>Comment/Remark</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>End cap Size (state)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>End cap Material (UV stabilized insulation rubber)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Design or Construction (Suitably designed for sealing the open ends of insulated conductors against water ingress)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Installation (Can be held in installed position by elastic forces)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Finish (Smooth and uniform thickness without any sharp edges)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Test certificates (Routine, type tests) provide</td>\n<td>&nbsp;</td>\n</tr>\n</tbody>\n</table>\n<h6>Write a brief comment on Material(s):</h6>\n</div>', -1, ' -> Kwesiga Kato -> Kwesiga Kato'),
(110, 'ABC end cap', 'dd', 'Visual', 3, 3, 3, 333, '33', '333', '2023-01-28', '2023-01-28', NULL, '<div>\n<table>\n<thead>\n<tr>\n<th>Umeme Requirements</th>\n<th>Comment/Remark</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>End cap Size (state)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>End cap Material (UV stabilized insulation rubber)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Design or Construction (Suitably designed for sealing the open ends of insulated conductors against water ingress)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Installation (Can be held in installed position by elastic forces)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Finish (Smooth and uniform thickness without any sharp edges)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Test certificates (Routine, type tests) provide</td>\n<td>&nbsp;</td>\n</tr>\n</tbody>\n</table>\n<h6>Write a brief comment on Material(s):</h6>\n</div>', -1, ' -> Kwesiga Kato -> Kwesiga Kato'),
(111, 'ABC end cap', 'xx', 'Testing', 3, 22, 22, 2, '33333', '333', '2023-01-28', '2023-01-28', NULL, '<div>\n<table>\n<thead>\n<tr>\n<th>Umeme Requirements</th>\n<th>Comment/Remark</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>End cap Size (state)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>End cap Material (UV stabilized insulation rubber)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Design or Construction (Suitably designed for sealing the open ends of insulated conductors against water ingress)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Installation (Can be held in installed position by elastic forces)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Finish (Smooth and uniform thickness without any sharp edges)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Test certificates (Routine, type tests) provide</td>\n<td>&nbsp;</td>\n</tr>\n</tbody>\n</table>\n<h6>Write a brief comment on Material(s):</h6>\n</div>', 0, ''),
(112, 'cordless drilling machine', 'Apex Suppliers', 'Measurement', 33, 400, 398, 12, 'Delivery', 'DFB2345', '2023-01-17', '2023-02-06', NULL, '<div>\n<table>\n<thead>\n<tr>\n<th>Umeme Requirements</th>\n<th>Comment/Remark</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>Width (2.8/71.12mm)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Chuck Size ( 1/4 in Hex)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Max Drilling Diameter (6mm/10mm-Steel,Wood &amp; Walls)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Drilling Bits (6mm/10mm drilling bits for Steel, Wood&amp;Walls)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Chuck Design (keyless)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Case Type (Bag/Plastic Casing)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Accessories (2- 18V Lithium-Ion FatPack Batteries, 1 - 45-Minute Lithium-ion Battery Fast Charger &amp; 1 - Carrying Case)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Battery Type (Lizthium ion</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Battery voltage (18V)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Test certificates (Routine, type tests, National accreditation of supplier)</td>\n<td>&nbsp;</td>\n</tr>\n</tbody>\n</table>\n<h6>Write a brief comment on Material(s):</h6>\n</div>', -1, ' -> Kwesiga Kato -> Kwesiga Kato'),
(113, 'cordless drilling machine', 'Apex Suppliers', 'Measurement', 33, 400, 398, 12, 'Delivery', 'DFB2345', '2023-01-17', '2023-02-06', NULL, '<div>\n<table>\n<thead>\n<tr>\n<th>Umeme Requirements</th>\n<th>Comment/Remark</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>Width (2.8/71.12mm)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Chuck Size ( 1/4 in Hex)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Max Drilling Diameter (6mm/10mm-Steel,Wood &amp; Walls)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Drilling Bits (6mm/10mm drilling bits for Steel, Wood&amp;Walls)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Chuck Design (keyless)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Case Type (Bag/Plastic Casing)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Accessories (2- 18V Lithium-Ion FatPack Batteries, 1 - 45-Minute Lithium-ion Battery Fast Charger &amp; 1 - Carrying Case)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Battery Type (Lizthium ion</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Battery voltage (18V)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Test certificates (Routine, type tests, National accreditation of supplier)</td>\n<td>&nbsp;</td>\n</tr>\n</tbody>\n</table>\n<h6>Write a brief comment on Material(s):</h6>\n</div>', 0, ''),
(114, 'cordless drilling machine', 'Apex Suppliers', 'Measurement', 33, 400, 398, 12, 'Delivery', 'DFB2345', '2023-01-17', '2023-02-06', NULL, '<div>\n<table>\n<thead>\n<tr>\n<th>Umeme Requirements</th>\n<th>Comment/Remark</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>Width (2.8/71.12mm)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Chuck Size ( 1/4 in Hex)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Max Drilling Diameter (6mm/10mm-Steel,Wood &amp; Walls)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Drilling Bits (6mm/10mm drilling bits for Steel, Wood&amp;Walls)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Chuck Design (keyless)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Case Type (Bag/Plastic Casing)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Accessories (2- 18V Lithium-Ion FatPack Batteries, 1 - 45-Minute Lithium-ion Battery Fast Charger &amp; 1 - Carrying Case)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Battery Type (Lizthium ion</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Battery voltage (18V)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Test certificates (Routine, type tests, National accreditation of supplier)</td>\n<td>&nbsp;</td>\n</tr>\n</tbody>\n</table>\n<h6>Write a brief comment on Material(s):</h6>\n</div>', 0, ''),
(115, 'cordless drilling machine', 'Apex Suppliers', 'Measurement', 33, 400, 398, 12, 'Delivery', 'DFB2345', '2023-01-17', '2023-02-06', NULL, '<div>\n<table>\n<thead>\n<tr>\n<th>Umeme Requirements</th>\n<th>Comment/Remark</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>Width (2.8/71.12mm)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Chuck Size ( 1/4 in Hex)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Max Drilling Diameter (6mm/10mm-Steel,Wood &amp; Walls)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Drilling Bits (6mm/10mm drilling bits for Steel, Wood&amp;Walls)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Chuck Design (keyless)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Case Type (Bag/Plastic Casing)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Accessories (2- 18V Lithium-Ion FatPack Batteries, 1 - 45-Minute Lithium-ion Battery Fast Charger &amp; 1 - Carrying Case)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Battery Type (Lizthium ion</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Battery voltage (18V)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Test certificates (Routine, type tests, National accreditation of supplier)</td>\n<td>&nbsp;</td>\n</tr>\n</tbody>\n</table>\n<h6>Write a brief comment on Material(s):</h6>\n</div>', 0, ''),
(116, 'cordless drilling machine', 'Apex Suppliers', 'Measurement', 33, 400, 398, 12, 'Delivery', 'DFB2345', '2023-01-17', '2023-02-06', NULL, '<div>\n<table>\n<thead>\n<tr>\n<th>Umeme Requirements</th>\n<th>Comment/Remark</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>Width (2.8/71.12mm)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Chuck Size ( 1/4 in Hex)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Max Drilling Diameter (6mm/10mm-Steel,Wood &amp; Walls)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Drilling Bits (6mm/10mm drilling bits for Steel, Wood&amp;Walls)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Chuck Design (keyless)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Case Type (Bag/Plastic Casing)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Accessories (2- 18V Lithium-Ion FatPack Batteries, 1 - 45-Minute Lithium-ion Battery Fast Charger &amp; 1 - Carrying Case)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Battery Type (Lizthium ion</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Battery voltage (18V)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Test certificates (Routine, type tests, National accreditation of supplier)</td>\n<td>&nbsp;</td>\n</tr>\n</tbody>\n</table>\n<h6>Write a brief comment on Material(s):</h6>\n</div>', 0, ''),
(117, 'cordless drilling machine', 'Apex Suppliers', 'Measurement', 33, 400, 398, 12, 'Delivery', 'DFB2345', '2023-01-17', '2023-02-06', NULL, '<div>\n<table>\n<thead>\n<tr>\n<th>Umeme Requirements</th>\n<th>Comment/Remark</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>Width (2.8/71.12mm)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Chuck Size ( 1/4 in Hex)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Max Drilling Diameter (6mm/10mm-Steel,Wood &amp; Walls)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Drilling Bits (6mm/10mm drilling bits for Steel, Wood&amp;Walls)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Chuck Design (keyless)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Case Type (Bag/Plastic Casing)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Accessories (2- 18V Lithium-Ion FatPack Batteries, 1 - 45-Minute Lithium-ion Battery Fast Charger &amp; 1 - Carrying Case)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Battery Type (Lizthium ion</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Battery voltage (18V)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Test certificates (Routine, type tests, National accreditation of supplier)</td>\n<td>&nbsp;</td>\n</tr>\n</tbody>\n</table>\n<h6>Write a brief comment on Material(s):</h6>\n</div>', 0, ''),
(118, 'cordless drilling machine', 'Apex Suppliers', 'Measurement', 33, 400, 398, 12, 'Delivery', 'DFB2345', '2023-01-17', '2023-02-06', NULL, '<div>\n<table>\n<thead>\n<tr>\n<th>Umeme Requirements</th>\n<th>Comment/Remark</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>Width (2.8/71.12mm)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Chuck Size ( 1/4 in Hex)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Max Drilling Diameter (6mm/10mm-Steel,Wood &amp; Walls)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Drilling Bits (6mm/10mm drilling bits for Steel, Wood&amp;Walls)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Chuck Design (keyless)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Case Type (Bag/Plastic Casing)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Accessories (2- 18V Lithium-Ion FatPack Batteries, 1 - 45-Minute Lithium-ion Battery Fast Charger &amp; 1 - Carrying Case)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Battery Type (Lizthium ion</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Battery voltage (18V)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Test certificates (Routine, type tests, National accreditation of supplier)</td>\n<td>&nbsp;</td>\n</tr>\n</tbody>\n</table>\n<h6>Write a brief comment on Material(s):</h6>\n</div>', 0, ''),
(119, 'cordless drilling machine', 'Apex Suppliers', 'Measurement', 33, 400, 398, 12, 'Delivery', 'DFB2345', '2023-01-17', '2023-02-06', NULL, '<div>\n<table>\n<thead>\n<tr>\n<th>Umeme Requirements</th>\n<th>Comment/Remark</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>Width (2.8/71.12mm)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Chuck Size ( 1/4 in Hex)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Max Drilling Diameter (6mm/10mm-Steel,Wood &amp; Walls)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Drilling Bits (6mm/10mm drilling bits for Steel, Wood&amp;Walls)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Chuck Design (keyless)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Case Type (Bag/Plastic Casing)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Accessories (2- 18V Lithium-Ion FatPack Batteries, 1 - 45-Minute Lithium-ion Battery Fast Charger &amp; 1 - Carrying Case)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Battery Type (Lizthium ion</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Battery voltage (18V)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Test certificates (Routine, type tests, National accreditation of supplier)</td>\n<td>&nbsp;</td>\n</tr>\n</tbody>\n</table>\n<h6>Write a brief comment on Material(s):</h6>\n</div>', 0, ''),
(120, 'cordless drilling machine', 'Apex Suppliers', 'Measurement', 33, 400, 398, 12, 'Delivery', 'DFB2345', '2023-01-17', '2023-02-06', NULL, '<div>\n<table>\n<thead>\n<tr>\n<th>Umeme Requirements</th>\n<th>Comment/Remark</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>Width (2.8/71.12mm)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Chuck Size ( 1/4 in Hex)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Max Drilling Diameter (6mm/10mm-Steel,Wood &amp; Walls)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Drilling Bits (6mm/10mm drilling bits for Steel, Wood&amp;Walls)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Chuck Design (keyless)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Case Type (Bag/Plastic Casing)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Accessories (2- 18V Lithium-Ion FatPack Batteries, 1 - 45-Minute Lithium-ion Battery Fast Charger &amp; 1 - Carrying Case)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Battery Type (Lizthium ion</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Battery voltage (18V)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Test certificates (Routine, type tests, National accreditation of supplier)</td>\n<td>&nbsp;</td>\n</tr>\n</tbody>\n</table>\n<h6>Write a brief comment on Material(s):</h6>\n</div>', 0, ''),
(121, 'cordless drilling machine', 'Apex Suppliers', 'Measurement', 33, 400, 398, 12, 'Delivery', 'DFB2345', '2023-01-17', '2023-02-06', NULL, '<div>\n<table>\n<thead>\n<tr>\n<th>Umeme Requirements</th>\n<th>Comment/Remark</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>Width (2.8/71.12mm)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Chuck Size ( 1/4 in Hex)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Max Drilling Diameter (6mm/10mm-Steel,Wood &amp; Walls)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Drilling Bits (6mm/10mm drilling bits for Steel, Wood&amp;Walls)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Chuck Design (keyless)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Case Type (Bag/Plastic Casing)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Accessories (2- 18V Lithium-Ion FatPack Batteries, 1 - 45-Minute Lithium-ion Battery Fast Charger &amp; 1 - Carrying Case)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Battery Type (Lizthium ion</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Battery voltage (18V)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Test certificates (Routine, type tests, National accreditation of supplier)</td>\n<td>&nbsp;</td>\n</tr>\n</tbody>\n</table>\n<h6>Write a brief comment on Material(s):</h6>\n</div>', -1, ' -> Kwesiga Kato -> Kwesiga Kato'),
(122, 'cordless drilling machine', 'ABC Suppliers', 'Measurement', 33, 400, 398, 12, 'Delivery', 'DFB2345', '2023-01-17', '2023-02-06', NULL, '<div>\n<table>\n<thead>\n<tr>\n<th>Umeme Requirements</th>\n<th>Comment/Remark</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>Width (2.8/71.12mm)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Chuck Size ( 1/4 in Hex)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Max Drilling Diameter (6mm/10mm-Steel,Wood &amp; Walls)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Drilling Bits (6mm/10mm drilling bits for Steel, Wood&amp;Walls)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Chuck Design (keyless)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Case Type (Bag/Plastic Casing)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Accessories (2- 18V Lithium-Ion FatPack Batteries, 1 - 45-Minute Lithium-ion Battery Fast Charger &amp; 1 - Carrying Case)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Battery Type (Lizthium ion</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Battery voltage (18V)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Test certificates (Routine, type tests, National accreditation of supplier)</td>\n<td>&nbsp;</td>\n</tr>\n</tbody>\n</table>\n<h6>Write a brief comment on Material(s):</h6>\n</div>', 0, ''),
(123, 'cordless drilling machine', 'ABC Suppliers', 'Measurement', 33, 400, 398, 12, 'Delivery', 'DFB2345', '2023-01-17', '2023-02-06', NULL, '<div>\n<table>\n<thead>\n<tr>\n<th>Umeme Requirements</th>\n<th>Comment/Remark</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>Width (2.8/71.12mm)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Chuck Size ( 1/4 in Hex)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Max Drilling Diameter (6mm/10mm-Steel,Wood &amp; Walls)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Drilling Bits (6mm/10mm drilling bits for Steel, Wood&amp;Walls)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Chuck Design (keyless)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Case Type (Bag/Plastic Casing)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Accessories (2- 18V Lithium-Ion FatPack Batteries, 1 - 45-Minute Lithium-ion Battery Fast Charger &amp; 1 - Carrying Case)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Battery Type (Lizthium ion</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Battery voltage (18V)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Test certificates (Routine, type tests, National accreditation of supplier)</td>\n<td>&nbsp;</td>\n</tr>\n</tbody>\n</table>\n<h6>Write a brief comment on Material(s):</h6>\n</div>', 0, ''),
(124, 'cordless drilling machine', 'ABC Suppliers', 'Measurement', 33, 400, 398, 12, 'Delivery', 'DFB2345', '2023-01-17', '2023-02-06', NULL, '<div>\n<table>\n<thead>\n<tr>\n<th>Umeme Requirements</th>\n<th>Comment/Remark</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>Width (2.8/71.12mm)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Chuck Size ( 1/4 in Hex)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Max Drilling Diameter (6mm/10mm-Steel,Wood &amp; Walls)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Drilling Bits (6mm/10mm drilling bits for Steel, Wood&amp;Walls)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Chuck Design (keyless)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Case Type (Bag/Plastic Casing)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Accessories (2- 18V Lithium-Ion FatPack Batteries, 1 - 45-Minute Lithium-ion Battery Fast Charger &amp; 1 - Carrying Case)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Battery Type (Lizthium ion</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Battery voltage (18V)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Test certificates (Routine, type tests, National accreditation of supplier)</td>\n<td>&nbsp;</td>\n</tr>\n</tbody>\n</table>\n<h6>Write a brief comment on Material(s):</h6>\n</div>', 0, ''),
(125, 'cordless drilling machine', 'ABC Suppliers', 'Measurement', 33, 400, 398, 12, 'Delivery', 'DFB2345', '2023-01-17', '2023-02-06', NULL, '<div>\n<table>\n<thead>\n<tr>\n<th>Umeme Requirements</th>\n<th>Comment/Remark</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>Width (2.8/71.12mm)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Chuck Size ( 1/4 in Hex)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Max Drilling Diameter (6mm/10mm-Steel,Wood &amp; Walls)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Drilling Bits (6mm/10mm drilling bits for Steel, Wood&amp;Walls)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Chuck Design (keyless)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Case Type (Bag/Plastic Casing)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Accessories (2- 18V Lithium-Ion FatPack Batteries, 1 - 45-Minute Lithium-ion Battery Fast Charger &amp; 1 - Carrying Case)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Battery Type (Lizthium ion</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Battery voltage (18V)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Test certificates (Routine, type tests, National accreditation of supplier)</td>\n<td>&nbsp;</td>\n</tr>\n</tbody>\n</table>\n<h6>Write a brief comment on Material(s):</h6>\n</div>', 0, ''),
(126, 'cordless drilling machine', 'ABC Suppliers', 'Measurement', 33, 400, 398, 12, 'Delivery', 'DFB2345', '2023-01-17', '2023-02-06', NULL, '<div>\n<table>\n<thead>\n<tr>\n<th>Umeme Requirements</th>\n<th>Comment/Remark</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>Width (2.8/71.12mm)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Chuck Size ( 1/4 in Hex)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Max Drilling Diameter (6mm/10mm-Steel,Wood &amp; Walls)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Drilling Bits (6mm/10mm drilling bits for Steel, Wood&amp;Walls)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Chuck Design (keyless)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Case Type (Bag/Plastic Casing)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Accessories (2- 18V Lithium-Ion FatPack Batteries, 1 - 45-Minute Lithium-ion Battery Fast Charger &amp; 1 - Carrying Case)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Battery Type (Lizthium ion</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Battery voltage (18V)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Test certificates (Routine, type tests, National accreditation of supplier)</td>\n<td>&nbsp;</td>\n</tr>\n</tbody>\n</table>\n<h6>Write a brief comment on Material(s):</h6>\n</div>', -1, ' -> Kwesiga Kato'),
(127, 'cordless drilling machine', 'ABC Suppliers', 'Measurement', 33, 400, 398, 12, 'Delivery', 'DFB2345', '2023-01-17', '2023-02-06', NULL, '<div>\n<table>\n<thead>\n<tr>\n<th>Umeme Requirements</th>\n<th>Comment/Remark</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>Width (2.8/71.12mm)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Chuck Size ( 1/4 in Hex)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Max Drilling Diameter (6mm/10mm-Steel,Wood &amp; Walls)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Drilling Bits (6mm/10mm drilling bits for Steel, Wood&amp;Walls)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Chuck Design (keyless)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Case Type (Bag/Plastic Casing)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Accessories (2- 18V Lithium-Ion FatPack Batteries, 1 - 45-Minute Lithium-ion Battery Fast Charger &amp; 1 - Carrying Case)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Battery Type (Lizthium ion</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Battery voltage (18V)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Test certificates (Routine, type tests, National accreditation of supplier)</td>\n<td>&nbsp;</td>\n</tr>\n</tbody>\n</table>\n<h6>Write a brief comment on Material(s):</h6>\n</div>', -1, ' -> Kwesiga Kato -> Kwesiga Kato -> Kwesiga Kato -> Kwesiga Kato -> Kwesiga Kato'),
(128, 'cordless drilling machine', 'ABC Suppliers', 'Measurement', 33, 400, 398, 12, 'Delivery', 'DFB2345', '2023-01-17', '2023-02-06', NULL, '<div>\n<table>\n<thead>\n<tr>\n<th>Umeme Requirements</th>\n<th>Comment/Remark</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>Width (2.8/71.12mm)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Chuck Size ( 1/4 in Hex)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Max Drilling Diameter (6mm/10mm-Steel,Wood &amp; Walls)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Drilling Bits (6mm/10mm drilling bits for Steel, Wood&amp;Walls)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Chuck Design (keyless)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Case Type (Bag/Plastic Casing)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Accessories (2- 18V Lithium-Ion FatPack Batteries, 1 - 45-Minute Lithium-ion Battery Fast Charger &amp; 1 - Carrying Case)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Battery Type (Lizthium ion</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Battery voltage (18V)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Test certificates (Routine, type tests, National accreditation of supplier)</td>\n<td>&nbsp;</td>\n</tr>\n</tbody>\n</table>\n<h6>Write a brief comment on Material(s):</h6>\n</div>', 0, ''),
(129, 'cordless drilling machine', 'ABC Suppliers', 'Measurement', 33, 400, 398, 12, 'Delivery', 'DFB2345', '2023-01-17', '2023-02-06', NULL, '<div>\n<table>\n<thead>\n<tr>\n<th>Umeme Requirements</th>\n<th>Comment/Remark</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>Width (2.8/71.12mm)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Chuck Size ( 1/4 in Hex)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Max Drilling Diameter (6mm/10mm-Steel,Wood &amp; Walls)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Drilling Bits (6mm/10mm drilling bits for Steel, Wood&amp;Walls)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Chuck Design (keyless)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Case Type (Bag/Plastic Casing)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Accessories (2- 18V Lithium-Ion FatPack Batteries, 1 - 45-Minute Lithium-ion Battery Fast Charger &amp; 1 - Carrying Case)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Battery Type (Lizthium ion</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Battery voltage (18V)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Test certificates (Routine, type tests, National accreditation of supplier)</td>\n<td>&nbsp;</td>\n</tr>\n</tbody>\n</table>\n<h6>Write a brief comment on Material(s):</h6>\n</div>', 0, ''),
(130, 'cordless drilling machine', 'ABC Suppliers', 'Measurement', 33, 400, 398, 12, 'Delivery', 'DFB2345', '2023-01-17', '2023-02-06', NULL, '<div>\n<table>\n<thead>\n<tr>\n<th>Umeme Requirements</th>\n<th>Comment/Remark</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>Width (2.8/71.12mm)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Chuck Size ( 1/4 in Hex)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Max Drilling Diameter (6mm/10mm-Steel,Wood &amp; Walls)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Drilling Bits (6mm/10mm drilling bits for Steel, Wood&amp;Walls)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Chuck Design (keyless)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Case Type (Bag/Plastic Casing)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Accessories (2- 18V Lithium-Ion FatPack Batteries, 1 - 45-Minute Lithium-ion Battery Fast Charger &amp; 1 - Carrying Case)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Battery Type (Lizthium ion</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Battery voltage (18V)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Test certificates (Routine, type tests, National accreditation of supplier)</td>\n<td>&nbsp;</td>\n</tr>\n</tbody>\n</table>\n<h6>Write a brief comment on Material(s):</h6>\n</div>', 0, ''),
(131, 'cordless drilling machine', 'ABC Suppliers', 'Measurement', 33, 400, 398, 12, 'Delivery', 'DFB2345', '2023-01-17', '2023-02-06', NULL, '<div>\n<table>\n<thead>\n<tr>\n<th>Umeme Requirements</th>\n<th>Comment/Remark</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>Width (2.8/71.12mm)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Chuck Size ( 1/4 in Hex)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Max Drilling Diameter (6mm/10mm-Steel,Wood &amp; Walls)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Drilling Bits (6mm/10mm drilling bits for Steel, Wood&amp;Walls)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Chuck Design (keyless)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Case Type (Bag/Plastic Casing)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Accessories (2- 18V Lithium-Ion FatPack Batteries, 1 - 45-Minute Lithium-ion Battery Fast Charger &amp; 1 - Carrying Case)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Battery Type (Lizthium ion</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Battery voltage (18V)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Test certificates (Routine, type tests, National accreditation of supplier)</td>\n<td>&nbsp;</td>\n</tr>\n</tbody>\n</table>\n<h6>Write a brief comment on Material(s):</h6>\n</div>', 0, ''),
(132, 'cordless drilling machine', 'ABC Suppliers', 'Measurement', 33, 400, 398, 12, 'Delivery', 'DFB2345', '2023-01-17', '2023-02-06', NULL, '<div>\n<table>\n<thead>\n<tr>\n<th>Umeme Requirements</th>\n<th>Comment/Remark</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>Width (2.8/71.12mm)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Chuck Size ( 1/4 in Hex)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Max Drilling Diameter (6mm/10mm-Steel,Wood &amp; Walls)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Drilling Bits (6mm/10mm drilling bits for Steel, Wood&amp;Walls)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Chuck Design (keyless)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Case Type (Bag/Plastic Casing)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Accessories (2- 18V Lithium-Ion FatPack Batteries, 1 - 45-Minute Lithium-ion Battery Fast Charger &amp; 1 - Carrying Case)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Battery Type (Lizthium ion</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Battery voltage (18V)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Test certificates (Routine, type tests, National accreditation of supplier)</td>\n<td>&nbsp;</td>\n</tr>\n</tbody>\n</table>\n<h6>Write a brief comment on Material(s):</h6>\n</div>', 0, ''),
(133, 'cordless drilling machine', 'ABC Suppliers', 'Measurement', 33, 400, 398, 12, 'Delivery', 'DFB2345', '2023-01-17', '2023-02-06', NULL, '<div>\n<table>\n<thead>\n<tr>\n<th>Umeme Requirements</th>\n<th>Comment/Remark</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>Width (2.8/71.12mm)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Chuck Size ( 1/4 in Hex)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Max Drilling Diameter (6mm/10mm-Steel,Wood &amp; Walls)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Drilling Bits (6mm/10mm drilling bits for Steel, Wood&amp;Walls)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Chuck Design (keyless)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Case Type (Bag/Plastic Casing)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Accessories (2- 18V Lithium-Ion FatPack Batteries, 1 - 45-Minute Lithium-ion Battery Fast Charger &amp; 1 - Carrying Case)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Battery Type (Lizthium ion</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Battery voltage (18V)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Test certificates (Routine, type tests, National accreditation of supplier)</td>\n<td>&nbsp;</td>\n</tr>\n</tbody>\n</table>\n<h6>Write a brief comment on Material(s):</h6>\n</div>', 0, ''),
(134, 'cordless drilling machine', 'ABC Suppliers', 'Measurement', 33, 400, 398, 12, 'Delivery', 'DFB2345', '2023-01-17', '2023-02-06', NULL, '<div>\n<table>\n<thead>\n<tr>\n<th>Umeme Requirements</th>\n<th>Comment/Remark</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>Width (2.8/71.12mm)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Chuck Size ( 1/4 in Hex)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Max Drilling Diameter (6mm/10mm-Steel,Wood &amp; Walls)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Drilling Bits (6mm/10mm drilling bits for Steel, Wood&amp;Walls)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Chuck Design (keyless)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Case Type (Bag/Plastic Casing)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Accessories (2- 18V Lithium-Ion FatPack Batteries, 1 - 45-Minute Lithium-ion Battery Fast Charger &amp; 1 - Carrying Case)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Battery Type (Lizthium ion</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Battery voltage (18V)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Test certificates (Routine, type tests, National accreditation of supplier)</td>\n<td>&nbsp;</td>\n</tr>\n</tbody>\n</table>\n<h6>Write a brief comment on Material(s):</h6>\n</div>', 0, ''),
(135, 'cordless drilling machine', 'ABC Suppliers', 'Measurement', 33, 400, 398, 12, 'Delivery', 'DFB2345', '2023-01-17', '2023-02-06', NULL, '<div>\n<table>\n<thead>\n<tr>\n<th>Umeme Requirements</th>\n<th>Comment/Remark</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>Width (2.8/71.12mm)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Chuck Size ( 1/4 in Hex)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Max Drilling Diameter (6mm/10mm-Steel,Wood &amp; Walls)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Drilling Bits (6mm/10mm drilling bits for Steel, Wood&amp;Walls)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Chuck Design (keyless)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Case Type (Bag/Plastic Casing)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Accessories (2- 18V Lithium-Ion FatPack Batteries, 1 - 45-Minute Lithium-ion Battery Fast Charger &amp; 1 - Carrying Case)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Battery Type (Lizthium ion</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Battery voltage (18V)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Test certificates (Routine, type tests, National accreditation of supplier)</td>\n<td>&nbsp;</td>\n</tr>\n</tbody>\n</table>\n<h6>Write a brief comment on Material(s):</h6>\n</div>', 0, ''),
(136, 'cordless drilling machine', 'ABC Suppliers', 'Measurement', 33, 400, 398, 12, 'Delivery', 'DFB2345', '2023-01-17', '2023-02-06', NULL, '<div>\n<table>\n<thead>\n<tr>\n<th>Umeme Requirements</th>\n<th>Comment/Remark</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>Width (2.8/71.12mm)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Chuck Size ( 1/4 in Hex)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Max Drilling Diameter (6mm/10mm-Steel,Wood &amp; Walls)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Drilling Bits (6mm/10mm drilling bits for Steel, Wood&amp;Walls)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Chuck Design (keyless)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Case Type (Bag/Plastic Casing)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Accessories (2- 18V Lithium-Ion FatPack Batteries, 1 - 45-Minute Lithium-ion Battery Fast Charger &amp; 1 - Carrying Case)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Battery Type (Lizthium ion</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Battery voltage (18V)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Test certificates (Routine, type tests, National accreditation of supplier)</td>\n<td>&nbsp;</td>\n</tr>\n</tbody>\n</table>\n<h6>Write a brief comment on Material(s):</h6>\n</div>', 0, ''),
(137, 'cordless drilling machine', 'ABC Suppliers', 'Measurement', 33, 400, 398, 12, 'Delivery', 'DFB2345', '2023-01-17', '2023-02-06', NULL, '<div>\n<table>\n<thead>\n<tr>\n<th>Umeme Requirements</th>\n<th>Comment/Remark</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>Width (2.8/71.12mm)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Chuck Size ( 1/4 in Hex)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Max Drilling Diameter (6mm/10mm-Steel,Wood &amp; Walls)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Drilling Bits (6mm/10mm drilling bits for Steel, Wood&amp;Walls)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Chuck Design (keyless)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Case Type (Bag/Plastic Casing)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Accessories (2- 18V Lithium-Ion FatPack Batteries, 1 - 45-Minute Lithium-ion Battery Fast Charger &amp; 1 - Carrying Case)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Battery Type (Lizthium ion</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Battery voltage (18V)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Test certificates (Routine, type tests, National accreditation of supplier)</td>\n<td>&nbsp;</td>\n</tr>\n</tbody>\n</table>\n<h6>Write a brief comment on Material(s):</h6>\n</div>', 0, ''),
(138, 'cordless drilling machine', 'ABC Suppliers', 'Measurement', 33, 400, 398, 12, 'Delivery', 'DFB2345', '2023-01-17', '2023-02-06', NULL, '<div>\n<table>\n<thead>\n<tr>\n<th>Umeme Requirements</th>\n<th>Comment/Remark</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>Width (2.8/71.12mm)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Chuck Size ( 1/4 in Hex)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Max Drilling Diameter (6mm/10mm-Steel,Wood &amp; Walls)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Drilling Bits (6mm/10mm drilling bits for Steel, Wood&amp;Walls)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Chuck Design (keyless)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Case Type (Bag/Plastic Casing)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Accessories (2- 18V Lithium-Ion FatPack Batteries, 1 - 45-Minute Lithium-ion Battery Fast Charger &amp; 1 - Carrying Case)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Battery Type (Lizthium ion</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Battery voltage (18V)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Test certificates (Routine, type tests, National accreditation of supplier)</td>\n<td>&nbsp;</td>\n</tr>\n</tbody>\n</table>\n<h6>Write a brief comment on Material(s):</h6>\n</div>', 0, ''),
(139, 'cordless drilling machine', 'ABC Suppliers', 'Measurement', 33, 400, 398, 12, 'Delivery', 'DFB2345', '2023-01-17', '2023-02-06', NULL, '<div>\n<table>\n<thead>\n<tr>\n<th>Umeme Requirements</th>\n<th>Comment/Remark</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>Width (2.8/71.12mm)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Chuck Size ( 1/4 in Hex)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Max Drilling Diameter (6mm/10mm-Steel,Wood &amp; Walls)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Drilling Bits (6mm/10mm drilling bits for Steel, Wood&amp;Walls)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Chuck Design (keyless)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Case Type (Bag/Plastic Casing)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Accessories (2- 18V Lithium-Ion FatPack Batteries, 1 - 45-Minute Lithium-ion Battery Fast Charger &amp; 1 - Carrying Case)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Battery Type (Lizthium ion</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Battery voltage (18V)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Test certificates (Routine, type tests, National accreditation of supplier)</td>\n<td>&nbsp;</td>\n</tr>\n</tbody>\n</table>\n<h6>Write a brief comment on Material(s):</h6>\n</div>', 0, ''),
(140, 'D-Iron', 'ABC Suppliers', 'Measurement', 33, 400, 398, 12, 'Delivery', 'DFB2345', '2023-01-17', '2023-02-06', NULL, '<div>\n<table>\n<thead>\n<tr>\n<th>Umeme Requirements</th>\n<th>Comment/Remark</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>Material (Hot Dip Galvanised Steel)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>D-Iron Manufacture (Drop Forged Manufacture)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Thickness of D-Iron Body (mm)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Width of D-Iron Body (mm)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Approxmate Over Length of D-Iron (330mm)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Number and Diameter of Holes (3 of D18mm)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>D-Iron Finish (Smooth Galvanised Finish)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Test certificates (Routine, type tests, National accreditation of supplier)</td>\n<td>&nbsp;</td>\n</tr>\n</tbody>\n</table>\n<h6>Write a brief comment on Material(s):</h6>\n</div>', 0, ''),
(141, 'D-Iron', 'ABC Suppliers', 'Measurement', 33, 400, 398, 12, 'Delivery', 'DFB2345', '2023-01-17', '2023-02-06', NULL, '<div>\n<table>\n<thead>\n<tr>\n<th>Umeme Requirements</th>\n<th>Comment/Remark</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>Material (Hot Dip Galvanised Steel)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>D-Iron Manufacture (Drop Forged Manufacture)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Thickness of D-Iron Body (mm)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Width of D-Iron Body (mm)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Approxmate Over Length of D-Iron (330mm)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Number and Diameter of Holes (3 of D18mm)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>D-Iron Finish (Smooth Galvanised Finish)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Test certificates (Routine, type tests, National accreditation of supplier)</td>\n<td>&nbsp;</td>\n</tr>\n</tbody>\n</table>\n<h6>Write a brief comment on Material(s):</h6>\n</div>', 0, ''),
(142, 'D-Iron', 'ABC Suppliers', 'Measurement', 33, 400, 398, 12, 'Delivery', 'DFB2345', '2023-01-17', '2023-02-06', NULL, '<div>\n<table>\n<thead>\n<tr>\n<th>Umeme Requirements</th>\n<th>Comment/Remark</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>Material (Hot Dip Galvanised Steel)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>D-Iron Manufacture (Drop Forged Manufacture)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Thickness of D-Iron Body (mm)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Width of D-Iron Body (mm)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Approxmate Over Length of D-Iron (330mm)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Number and Diameter of Holes (3 of D18mm)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>D-Iron Finish (Smooth Galvanised Finish)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Test certificates (Routine, type tests, National accreditation of supplier)</td>\n<td>&nbsp;</td>\n</tr>\n</tbody>\n</table>\n<h6>Write a brief comment on Material(s):</h6>\n</div>', 0, ''),
(143, 'cable saddle', 'q&a suppliers', 'Visual', 22, 222, 123, 2, 'eeeee', 'eeee', '2023-01-14', '2023-01-18', NULL, '<div>\n<table>\n<thead>\n<tr>\n<th>Umeme Requirements</th>\n<th>Comment/Remark</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td>Cable saddle Size (mm)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Cable saddle design (Single, Double, Trefoil)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Cable saddle materia (33% glass fiber reinforced polyamide resin)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Cable saddle colour (Carbon black ultraviolet light absorber)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Cable saddle hole diameter (mm)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Cable saddle Finish (Shouldn\'t be damaged)</td>\n<td>&nbsp;</td>\n</tr>\n<tr>\n<td>Test certificates (Routine, type tests, National accreditation of supplier)</td>\n<td>&nbsp;</td>\n</tr>\n</tbody>\n</table>\n<h6>Write a brief comment on Material(s):</h6>\n</div>', 0, '');

-- --------------------------------------------------------

--
-- Table structure for table `poles`
--

CREATE TABLE `poles` (
  `observation` varchar(500) NOT NULL,
  `comment` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `poles`
--

INSERT INTO `poles` (`observation`, `comment`) VALUES
('nice', 'pass'),
('nice', 'pass'),
('hthth\'ssç', 'kato warenzya');

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `id` int(11) NOT NULL,
  `email` varchar(255) NOT NULL,
  `username` varchar(255) NOT NULL,
  `roles` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`roles`))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`id`, `email`, `username`, `roles`) VALUES
(8, 'u2211007@umeme.co.ug', 'katosteven', '{\"mit\":false,\"TCO\":true,\"MIT\":true}'),
(9, 'u2211008@umeme.co.ug', 'jamesbau', '{\"MIT\":true}'),
(10, 'hope.stella@umeme.co.ug', 'hopestellah', '{\"QAM\":true}'),
(11, 'admin@umeme.co.ug', 'admin', '{\"QAM\":true,\"LWM\":true}');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `checklists`
--
ALTER TABLE `checklists`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `checklisttest`
--
ALTER TABLE `checklisttest`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `email` (`email`),
  ADD UNIQUE KEY `username` (`username`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `checklists`
--
ALTER TABLE `checklists`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=18;

--
-- AUTO_INCREMENT for table `checklisttest`
--
ALTER TABLE `checklisttest`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=144;

--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=13;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
